In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# country_df = pd.read_csv("data\Country.csv")
# country_history_df = pd.read_csv("data\Country_History.csv")
county_df = pd.read_csv("data\County.csv")
county_history_df = pd.read_csv("data\County_History.csv")
# metro_df = pd.read_csv("data\Metro.csv")
# metro_history_df = pd.read_csv("data\Metro_History.csv")
state_df = pd.read_csv("data\State.csv")
state_history_df = pd.read_csv("data\State_History.csv")
# zip_df = pd.read_csv("data\Zip.csv")
# zip_history_df = pd.read_csv("data\Zip_History.csv")

In [3]:
county_history_df

,month_date_yyyymm,county_fips,county_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202506,45079,"richland, sc",289900.0,0.0000,-0.0333,1241.0,0.0891,0.2882,37.0,...,359136.0,-0.0120,-0.0324,2289.0,0.0228,0.1708,0.8460,-0.1189,-0.2090,0.0
1,202506,40085,"love, ok",323700.0,0.0195,0.2948,50.0,0.3026,0.4559,66.0,...,388866.0,-0.0454,0.0871,56.0,0.2065,0.3875,0.1414,-0.0691,-0.0351,0.0
2,202506,39057,"greene, oh",364000.0,0.0400,0.0196,217.0,-0.0069,-0.0378,36.0,...,402502.0,0.0319,0.0041,539.0,-0.0182,-0.0037,1.4896,-0.0379,0.1118,0.0
3,202506,19073,"greene, ia",176250.0,-0.0042,0.0602,34.0,-0.1410,0.0806,68.0,...,222163.0,-0.0556,-0.0108,46.0,-0.1415,0.1375,0.3582,-0.0008,0.0679,0.0
4,202506,31181,"webster, ne",174750.0,-0.1152,0.2527,13.0,-0.0714,0.4444,42.0,...,353275.0,-0.0143,0.7768,21.0,0.0789,0.4643,0.5769,0.2198,0.0214,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335188,201607,48233,"hutchinson, tx",105900.0,NaN,NaN,79.0,NaN,NaN,61.0,...,139006.0,NaN,NaN,121.0,NaN,NaN,0.5316,NaN,NaN,NaN
335189,201607,37035,"catawba, nc",209900.0,NaN,NaN,887.0,NaN,NaN,73.0,...,294663.0,NaN,NaN,948.0,NaN,NaN,0.0981,NaN,NaN,NaN
335190,201607,4015,"mohave, az",234900.0,NaN,NaN,1606.0,NaN,NaN,83.0,...,292296.0,NaN,NaN,1737.0,NaN,NaN,0.0834,NaN,NaN,NaN
335191,201607,37123,"montgomery, nc",329000.0,NaN,NaN,255.0,NaN,NaN,109.0,...,405866.0,NaN,NaN,279.0,NaN,NaN,0.0902,NaN,NaN,NaN
335192,201607,12071,"lee, fl",305900.0,NaN,NaN,7386.0,NaN,NaN,85.0,...,476566.0,NaN,NaN,10449.0,NaN,NaN,0.4157,NaN,NaN,NaN

In [4]:
state_history_df

,month_date_yyyymm,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202506,Kentucky,KY,315000,0.0003,0.0000,10693,0.0499,0.3001,50,...,398834,0.0035,0.0043,17401,0.0367,0.2047,0.6276,-0.0243,-0.1211,0.0
1,202506,West Virginia,WV,275000,0.0189,0.1134,3674,0.0868,0.1556,48,...,344764,0.0138,0.0448,6224,0.0410,0.0700,0.6963,-0.0685,-0.1278,0.0
2,202506,Idaho,ID,599000,0.0052,0.0328,9077,0.1366,0.2009,46,...,924644,0.0260,0.0258,13293,0.0820,0.1389,0.4664,-0.0648,-0.0672,0.0
3,202506,Texas,TX,378000,0.0080,-0.0052,138255,0.0490,0.2706,56,...,539255,-0.0019,-0.0136,179455,0.0276,0.2064,0.2995,-0.0269,-0.0696,0.0
4,202506,Virginia,VA,473914,-0.0023,0.0533,20273,0.0409,0.4013,39,...,663074,-0.0147,0.0021,32017,0.0159,0.2466,0.5839,-0.0374,-0.2073,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5503,201607,Kansas,KS,159000,NaN,NaN,10809,NaN,NaN,60,...,237786,NaN,NaN,12311,NaN,NaN,0.1381,NaN,NaN,NaN
5504,201607,Oregon,OR,359000,NaN,NaN,17213,NaN,NaN,47,...,480480,NaN,NaN,19018,NaN,NaN,0.1075,NaN,NaN,NaN
5505,201607,Georgia,GA,234900,NaN,NaN,61142,NaN,NaN,65,...,346839,NaN,NaN,76778,NaN,NaN,0.2693,NaN,NaN,NaN
5506,201607,New Jersey,NJ,312000,NaN,NaN,55386,NaN,NaN,71,...,476833,NaN,NaN,62017,NaN,NaN,0.1213,NaN,NaN,NaN
5507,201607,Illinois,IL,224900,NaN,NaN,61100,NaN,NaN,58,...,349042,NaN,NaN,90015,NaN,NaN,0.4776,NaN,NaN,NaN

In [5]:
state_history_df['month_date_yyyymm'] = pd.to_datetime(state_history_df['month_date_yyyymm'].astype(str), format='%Y%m')

In [6]:
state_history_df

,month_date_yyyymm,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,2025-06-01,Kentucky,KY,315000,0.0003,0.0000,10693,0.0499,0.3001,50,...,398834,0.0035,0.0043,17401,0.0367,0.2047,0.6276,-0.0243,-0.1211,0.0
1,2025-06-01,West Virginia,WV,275000,0.0189,0.1134,3674,0.0868,0.1556,48,...,344764,0.0138,0.0448,6224,0.0410,0.0700,0.6963,-0.0685,-0.1278,0.0
2,2025-06-01,Idaho,ID,599000,0.0052,0.0328,9077,0.1366,0.2009,46,...,924644,0.0260,0.0258,13293,0.0820,0.1389,0.4664,-0.0648,-0.0672,0.0
3,2025-06-01,Texas,TX,378000,0.0080,-0.0052,138255,0.0490,0.2706,56,...,539255,-0.0019,-0.0136,179455,0.0276,0.2064,0.2995,-0.0269,-0.0696,0.0
4,2025-06-01,Virginia,VA,473914,-0.0023,0.0533,20273,0.0409,0.4013,39,...,663074,-0.0147,0.0021,32017,0.0159,0.2466,0.5839,-0.0374,-0.2073,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5503,2016-07-01,Kansas,KS,159000,NaN,NaN,10809,NaN,NaN,60,...,237786,NaN,NaN,12311,NaN,NaN,0.1381,NaN,NaN,NaN
5504,2016-07-01,Oregon,OR,359000,NaN,NaN,17213,NaN,NaN,47,...,480480,NaN,NaN,19018,NaN,NaN,0.1075,NaN,NaN,NaN
5505,2016-07-01,Georgia,GA,234900,NaN,NaN,61142,NaN,NaN,65,...,346839,NaN,NaN,76778,NaN,NaN,0.2693,NaN,NaN,NaN
5506,2016-07-01,New Jersey,NJ,312000,NaN,NaN,55386,NaN,NaN,71,...,476833,NaN,NaN,62017,NaN,NaN,0.1213,NaN,NaN,NaN
5507,2016-07-01,Illinois,IL,224900,NaN,NaN,61100,NaN,NaN,58,...,349042,NaN,NaN,90015,NaN,NaN,0.4776,NaN,NaN,NaN

In [7]:
def customDescription(df: pd.DataFrame, numeric_only: bool = False):
    if numeric_only:
        df = df.select_dtypes(include=np.number)
    
    desc = pd.DataFrame(index=df.columns.to_list())
    desc['type'] = df.dtypes
    desc['count'] = df.count()
    desc['nunique'] = df.nunique()
    desc['null'] = df.isnull().sum()
    
    # Calculate mode and handle multiple modes
    modes = df.mode()
    desc['mode'] = np.nan  # Default to NaN
    for col in df.columns:
        if len(modes[col].dropna()) == 1:  # Single mode exists
            desc.loc[col, 'mode'] = modes[col].iloc[0]
        else:  # Multiple modes
            desc.loc[col, 'mode'] = np.nan

    # Calculate least frequent value
    desc['least_frequent'] = np.nan  # Default to NaN
    for col in df.columns:
        value_counts = df[col].value_counts(dropna=False)
        if not value_counts.empty:
            least_freq_count = value_counts.min()  # Find the minimum frequency
            least_freq_values = value_counts[value_counts == least_freq_count].index
            
            if len(least_freq_values) == 1:  # If exactly one least frequent value exists
                desc.loc[col, 'least_frequent'] = least_freq_values[0]
            else:  # Multiple least frequent values
                desc.loc[col, 'least_frequent'] = np.nan
    
    # Handle numeric columns
    numeric_cols = df.select_dtypes(include=np.number)
    if not numeric_cols.empty:
        numeric_desc = numeric_cols.describe().T.drop(columns=['count', 'std', '25%', '50%', '75%'], axis=1)
        for col in numeric_cols.columns:
            desc.loc[col, 'mean'] = numeric_desc.loc[col, 'mean']
            desc.loc[col, 'min'] = numeric_desc.loc[col, 'min']
            desc.loc[col, 'max'] = numeric_desc.loc[col, 'max']
    
    # Handle datetime columns
    datetime_cols = df.select_dtypes(include=['datetime64[ns]', 'datetime64[ns, UTC]'])
    for col in datetime_cols.columns:
        desc.loc[col, 'min'] = df[col].min()
        desc.loc[col, 'max'] = df[col].max()
    
    return desc

In [8]:
df = state_history_df.copy()

In [9]:
customDescription(df)

,type,count,nunique,null,mode,least_frequent,mean,min,max
month_date_yyyymm,datetime64[ns],5508,108,0,NaN,NaN,NaN,2016-07-01 00:00:00,2025-06-01 00:00:00
state,object,5508,51,0,NaN,NaN,NaN,NaN,NaN
state_id,object,5508,51,0,NaN,NaN,NaN,NaN,NaN
median_listing_price,int64,5508,2617,0,299900.0000,NaN,360216.386892,129913.0,886500.0
median_listing_price_mm,float64,4896,1001,612,0.0000,NaN,0.005309,-0.1038,0.1135
median_listing_price_yy,float64,4896,2151,612,0.0000,NaN,0.068814,-0.2071,0.4101
active_listing_count,int64,5508,5034,0,NaN,NaN,17650.938453,720.0,182589.0
active_listing_count_mm,float64,4896,2469,612,NaN,NaN,0.000232,-0.3074,0.6116
active_listing_count_yy,float64,4896,3822,612,NaN,NaN,-0.012367,-0.7173,2.3532
median_days_on_market,int64,5508,130,0,51.0000,NaN,58.554103,13.0,157.0
median_days_on_market_mm,float64,4896,2169,612,0.0000,NaN,0.008575,-0.6023,0.5873
median_days_on_market_yy,float64,4896,2508,612,0.0000,NaN,-0.006308,-0.7155,1.6271
new_listing_count,int64,5508,3840,0,NaN,NaN,8207.112564,290.0,53332.0
new_listing_count_mm,float64,4896,3400,612,NaN,NaN,0.015546,-0.6912,2.2457
new_listing_count_yy,float64,4896,3006,612,0.0000,NaN,-0.013270,-0.7398,2.0644
price_increased_count,int64,5508,1084,0,20.0000,NaN,599.119463,0.0,9466.0
price_increased_count_mm,float64,4892,2786,616,0.0000,NaN,0.063016,-1.0,63.0
price_increased_count_yy,float64,4894,3217,614,0.0000,NaN,0.144082,-1.0,57.0
price_increased_share,float64,5508,581,0,0.0055,NaN,0.014464,0.0,0.1302
price_increased_share_mm,float64,4896,364,612,-0.0003,NaN,-0.000098,-0.0702,0.1023
price_increased_share_yy,float64,4896,642,612,-0.0009,NaN,-0.000509,-0.1175,0.1029
price_reduced_count,int64,5508,3200,0,580.0000,NaN,5142.209150,72.0,71888.0
price_reduced_count_mm,float64,4896,3552,612,0.0000,NaN,0.026358,-0.7625,2.9498
price_reduced_count_yy,float64,4896,4064,612,0.0000,NaN,0.076649,-0.8464,5.7706
price_reduced_share,float64,5508,1909,0,NaN,NaN,0.132805,0.0254,0.4089
price_reduced_share_mm,float64,4896,1010,612,0.0007,NaN,0.000254,-0.1286,0.1132
price_reduced_share_yy,float64,4896,1594,612,NaN,NaN,0.002088,-0.2464,0.3025
pending_listing_count,float64,5481,4612,27,NaN,NaN,8550.248312,0.0,82071.0
pending_listing_count_mm,float64,4871,2898,637,NaN,NaN,0.024072,-0.9734,15.9403
pending_listing_count_yy,float64,4860,3786,648,NaN,NaN,0.228948,-0.9777,16.1045
median_listing_price_per_square_foot,int64,5508,478,0,117.0000,NaN,195.895062,79.0,737.0
median_listing_price_per_square_foot_mm,float64,4896,730,612,0.0027,NaN,0.005804,-0.1165,0.1178
median_listing_price_per_square_foot_yy,float64,4896,2066,612,0.0655,NaN,0.075114,-0.095,0.4914
median_square_feet,int64,5508,1059,0,2000.0000,NaN,1908.460784,987.0,2798.0
median_square_feet_mm,float64,4896,634,612,0.0000,NaN,-0.000336,-0.101,0.1784
median_square_feet_yy,float64,4896,1524,612,0.0000,NaN,-0.003240,-0.3058,0.2676
average_listing_price,int64,5508,5488,0,NaN,NaN,568693.404139,206417.0,1730505.0
average_listing_price_mm,float64,4896,1042,612,0.0006,NaN,0.005413,-0.4512,0.9244
average_listing_price_yy,float64,4896,2314,612,0.0529,NaN,0.066544,-0.3896,1.0508
total_listing_count,int64,5508,5173,0,NaN,NaN,26086.285403,803.0,231347.0
total_listing_count_mm,float64,4896,2350,612,NaN,NaN,0.001265,-0.3592,0.7739
total_listing_count_yy,float64,4896,3398,612,NaN,NaN,-0.019375,-0.4954,1.1688
pending_ratio,float64,5481,4443,27,NaN,NaN,0.578411,0.0,3.212
pending_ratio_mm,float64,4871,2272,637,NaN,NaN,0.002429,-0.8669,1.1954
pending_ratio_yy,float64,4861,3648,647,NaN,NaN,0.034240,-2.5872,2.5949
quality_flag,float64,4896,2,612,0.0000,1.0,0.024306,0.0,1.0

In [10]:
pd.set_option('display.max_columns', None)

In [11]:
df[df['state_id'] == 'WV']

,month_date_yyyymm,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
1,2025-06-01,West Virginia,WV,275000,0.0189,0.1134,3674,0.0868,0.1556,48,0.0556,-0.0306,1906,0.0203,0.0732,52,-0.1875,-0.4348,0.0065,-0.0017,-0.0053,1228,0.1164,0.2429,0.1529,0.0138,0.0229,2558.0,-0.0104,-0.0237,148,0.0104,0.0888,1803,0.0059,0.0207,344764,0.0138,0.0448,6224,0.0410,0.0700,0.6963,-0.0685,-0.1278,0.0
75,2025-05-01,West Virginia,WV,269900,0.0228,0.1251,3380,0.1030,0.1558,45,-0.0323,-0.0426,1868,0.0021,0.0950,64,0.2308,0.0667,0.0082,0.0011,0.0001,1100,0.2443,0.3189,0.1392,0.0203,0.0259,2585.0,0.0459,-0.0458,147,0.0133,0.0985,1792,0.0150,0.0175,340074,0.0248,0.0342,5979,0.0819,0.0572,0.7648,-0.0417,-0.1615,0.0
121,2025-04-01,West Virginia,WV,263881,0.0188,0.0995,3065,0.0495,0.0808,47,-0.2846,-0.0792,1864,0.1768,0.0664,52,-0.4583,-0.5873,0.0070,-0.0075,-0.0112,884,0.1818,0.0351,0.1188,0.0017,-0.0008,2472.0,0.1780,-0.0104,145,0.0082,0.0870,1766,0.0066,0.0193,331834,0.0272,0.0107,5527,0.1031,0.0392,0.8065,0.0880,-0.0743,0.0
156,2025-03-01,West Virginia,WV,259000,0.0486,0.0837,2920,-0.0363,0.0607,65,-0.1772,0.1017,1584,0.3846,-0.0594,96,0.1429,0.0000,0.0146,0.0002,0.0003,748,0.1000,0.0054,0.1171,0.0068,0.0023,2098.0,0.1180,-0.0446,144,0.0271,0.1150,1754,0.0218,-0.0048,323062,0.0377,-0.0055,5010,0.0173,0.0089,0.7185,0.0992,-0.0792,0.0
243,2025-02-01,West Virginia,WV,247000,-0.0006,0.0706,3030,-0.0814,0.0966,79,0.0064,0.0533,1144,0.1064,-0.1513,84,-0.1600,-0.1064,0.0143,-0.0022,-0.0016,680,0.0658,0.0366,0.1103,0.0058,0.0020,1877.0,0.0717,-0.0511,140,0.0098,0.1090,1717,-0.0032,-0.0191,311327,0.0025,-0.0213,4925,-0.0166,0.0407,0.6193,0.0885,-0.0964,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5271,2016-11-01,West Virginia,WV,155925,NaN,NaN,9084,NaN,NaN,95,NaN,NaN,1556,NaN,NaN,46,NaN,NaN,0.0039,NaN,NaN,1266,NaN,NaN,0.1082,NaN,NaN,1081.0,NaN,NaN,89,NaN,NaN,1760,NaN,NaN,212205,NaN,NaN,10144,NaN,NaN,0.1190,NaN,NaN,NaN
5318,2016-10-01,West Virginia,WV,159000,NaN,NaN,9442,NaN,NaN,90,NaN,NaN,1848,NaN,NaN,64,NaN,NaN,0.0054,NaN,NaN,1532,NaN,NaN,0.1235,NaN,NaN,1212.0,NaN,NaN,90,NaN,NaN,1764,NaN,NaN,212698,NaN,NaN,10635,NaN,NaN,0.1284,NaN,NaN,NaN
5380,2016-09-01,West Virginia,WV,159875,NaN,NaN,9606,NaN,NaN,87,NaN,NaN,1734,NaN,NaN,64,NaN,NaN,0.0050,NaN,NaN,1666,NaN,NaN,0.1317,NaN,NaN,1225.0,NaN,NaN,90,NaN,NaN,1773,NaN,NaN,213569,NaN,NaN,10807,NaN,NaN,0.1275,NaN,NaN,NaN
5426,2016-08-01,West Virginia,WV,161350,NaN,NaN,9591,NaN,NaN,82,NaN,NaN,2046,NaN,NaN,70,NaN,NaN,0.0054,NaN,NaN,1780,NaN,NaN,0.1378,NaN,NaN,1291.0,NaN,NaN,90,NaN,NaN,1781,NaN,NaN,215415,NaN,NaN,10867,NaN,NaN,0.1346,NaN,NaN,NaN
5488,2016-07-01,West Virginia,WV,164900,NaN,NaN,9571,NaN,NaN,79,NaN,NaN,1988,NaN,NaN,56,NaN,NaN,0.0042,NaN,NaN,1724,NaN,NaN,0.1330,NaN,NaN,1260.0,NaN,NaN,91,NaN,NaN,1787,NaN,NaN,216063,NaN,NaN,10822,NaN,NaN,0.1316,NaN,NaN,NaN

In [12]:
# Sort by state and month
df = df.sort_values(["state_id", "month_date_yyyymm"])

def recompute_mm(df, base_col, mm_col):
    # Compute pct_change
    df[mm_col] = df.groupby("state_id")[base_col].pct_change()
    
    # Replace inf values with the base_col (new month value)
    inf_mask = df[mm_col].replace([np.inf, -np.inf], np.nan).isna() & df[base_col].notna()
    df.loc[inf_mask, mm_col] = df.loc[inf_mask, base_col]

    return df

In [13]:
# You can loop over all *_mm cols systematically:
base_to_mm = {
    "median_listing_price": "median_listing_price_mm",
    "active_listing_count": "active_listing_count_mm",
    "median_days_on_market": "median_days_on_market_mm",
    "new_listing_count": "new_listing_count_mm",
    "price_increased_count": "price_increased_count_mm",
    "price_increased_share": "price_increased_share_mm",
    "price_reduced_count": "price_reduced_count_mm",
    "price_reduced_share": "price_reduced_share_mm",
    "pending_listing_count": "pending_listing_count_mm",
    "median_listing_price_per_square_foot": "median_listing_price_per_square_foot_mm",
    "median_square_feet": "median_square_feet_mm",
    "average_listing_price": "average_listing_price_mm",
    "total_listing_count": "total_listing_count_mm",
    "pending_ratio": "pending_ratio_mm"
}

for base, mm in base_to_mm.items():
    if base in df.columns and mm in df.columns:
        df = recompute_mm(df, base, mm)

In [14]:
df.reset_index(drop=True, inplace=True)
df.drop(columns=['quality_flag'], inplace=True, errors='ignore')
df

,month_date_yyyymm,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
0,2016-07-01,Alaska,AK,289000,289000.000000,NaN,3784,3784.000000,NaN,62,62.000000,NaN,1224,1224.000000,NaN,36,36.000000,NaN,0.0075,0.007500,NaN,1244,1244.000000,NaN,0.2416,0.241600,NaN,2.0,2.000000,NaN,164,164.000000,NaN,1800,1800.000000,NaN,331337,331337.000000,NaN,3784,3784.000000,NaN,0.0005,0.000500,NaN
1,2016-08-01,Alaska,AK,286375,-0.009083,NaN,3737,-0.012421,NaN,68,0.096774,NaN,1082,-0.116013,NaN,46,0.277778,NaN,0.0095,0.266667,NaN,1262,0.014469,NaN,0.2596,0.074503,NaN,3.0,0.500000,NaN,164,0.000000,NaN,1785,-0.008333,NaN,328825,-0.007581,NaN,3739,-0.011892,NaN,0.0007,0.400000,NaN
2,2016-09-01,Alaska,AK,284725,-0.005762,NaN,3635,-0.027295,NaN,71,0.044118,NaN,898,-0.170055,NaN,18,-0.608696,NaN,0.0040,-0.578947,NaN,1134,-0.101426,NaN,0.2431,-0.063559,NaN,4.0,0.333333,NaN,164,0.000000,NaN,1783,-0.001120,NaN,326394,-0.007393,NaN,3639,-0.026745,NaN,0.0011,0.571429,NaN
3,2016-10-01,Alaska,AK,279900,-0.016946,NaN,3297,-0.092985,NaN,79,0.112676,NaN,788,-0.122494,NaN,24,0.333333,NaN,0.0060,0.500000,NaN,896,-0.209877,NaN,0.2162,-0.110654,NaN,4.0,0.000000,NaN,163,-0.006098,NaN,1764,-0.010656,NaN,326889,0.001517,NaN,3301,-0.092883,NaN,0.0012,0.090909,NaN
4,2016-11-01,Alaska,AK,279700,-0.000715,NaN,2983,-0.095238,NaN,87,0.101266,NaN,600,-0.238579,NaN,12,-0.500000,NaN,0.0035,-0.416667,NaN,646,-0.279018,NaN,0.1778,-0.177613,NaN,4.0,0.000000,NaN,163,0.000000,NaN,1764,0.000000,NaN,328331,0.004411,NaN,2986,-0.095426,NaN,0.0012,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5503,2025-02-01,Wyoming,WY,459725,-0.000435,0.0229,1834,-0.041797,0.0956,88,-0.011236,-0.0112,594,0.060714,0.0919,0,-1.000000,-1.00,0.0000,-1.000000,-0.0045,304,0.020134,0.2459,0.1096,0.047801,0.0180,435.0,0.172507,-0.0492,209,0.019512,0.1043,2171,-0.014973,-0.0418,1198147,0.026985,0.2415,2252,-0.013146,0.0628,0.2370,0.224174,-0.0361
5504,2025-03-01,Wyoming,WY,459900,0.000381,0.0243,1826,-0.004362,0.1127,68,-0.227273,-0.0556,784,0.319865,0.1951,12,12.000000,-0.25,0.0041,0.004100,-0.0018,332,0.092105,0.4310,0.1058,-0.034672,0.0271,502.0,0.154023,-0.0652,208,-0.004785,0.0800,2176,0.002303,-0.0357,1166754,-0.026201,0.2582,2318,0.029307,0.0657,0.2749,0.159916,-0.0523
5505,2025-04-01,Wyoming,WY,476000,0.035008,0.0462,1945,0.065170,0.1421,57,-0.161765,-0.1172,942,0.201531,0.1135,16,0.333333,-0.20,0.0046,0.121951,-0.0019,388,0.168675,0.2357,0.1135,0.072779,0.0121,597.0,0.189243,0.0093,209,0.004808,0.0716,2204,0.012868,-0.0267,1108065,-0.050301,0.2097,2535,0.093615,0.1128,0.3067,0.115678,-0.0404
5506,2025-05-01,Wyoming,WY,495000,0.039916,0.0623,2208,0.135219,0.1820,51,-0.105263,0.0000,1028,0.091295,0.1762,12,-0.250000,0.00,0.0033,-0.282609,-0.0004,520,0.340206,0.3000,0.1354,0.192952,0.0166,615.0,0.030151,-0.0144,211,0.009569,0.0443,2216,0.005445,-0.0353,1064091,-0.039685,0.1772,2816,0.110848,0.1373,0.2785,-0.091947,-0.0555
5507,2025-06-01,Wyoming,WY,496741,0.003517,0.0458,2519,0.140851,0.1644,50,-0.019608,0.0638,1146,0.114786,0.1506,14,0.166667,0.75,0.0032,-0.030303,0.0011,682,0.311538,0.2724,0.1597,0.179468,0.0161,649.0,0.055285,0.0973,217,0.028436,0.0210,2209,-0.003159,-0.0222,1166952,0.096666,0.1760,3156,0.120739,0.1529,0.2575,-0.075404,-0.0157

In [15]:
customDescription(df)

,type,count,nunique,null,mode,least_frequent,mean,min,max
month_date_yyyymm,datetime64[ns],5508,108,0,NaN,NaN,NaN,2016-07-01 00:00:00,2025-06-01 00:00:00
state,object,5508,51,0,NaN,NaN,NaN,NaN,NaN
state_id,object,5508,51,0,NaN,NaN,NaN,NaN,NaN
median_listing_price,int64,5508,2617,0,299900.0000,NaN,360216.386892,129913.0,886500.0
median_listing_price_mm,float64,5508,4792,0,0.0000,NaN,2476.961124,-0.103768,649000.0
median_listing_price_yy,float64,4896,2151,612,0.0000,NaN,0.068814,-0.2071,0.4101
active_listing_count,int64,5508,5034,0,NaN,NaN,17650.938453,720.0,182589.0
active_listing_count_mm,float64,5508,5502,0,NaN,NaN,265.792889,-0.307421,136780.0
active_listing_count_yy,float64,4896,3822,612,NaN,NaN,-0.012367,-0.7173,2.3532
median_days_on_market,int64,5508,130,0,51.0000,NaN,58.554103,13.0,157.0
median_days_on_market_mm,float64,5508,1392,0,0.0000,NaN,0.599418,-0.604651,89.0
median_days_on_market_yy,float64,4896,2508,612,0.0000,NaN,-0.006308,-0.7155,1.6271
new_listing_count,int64,5508,3840,0,NaN,NaN,8207.112564,290.0,53332.0
new_listing_count_mm,float64,5508,5458,0,0.0000,NaN,91.850143,-0.691244,47100.0
new_listing_count_yy,float64,4896,3006,612,0.0000,NaN,-0.013270,-0.7398,2.0644
price_increased_count,int64,5508,1084,0,20.0000,NaN,599.119463,0.0,9466.0
price_increased_count_mm,float64,5508,3466,0,0.0000,NaN,8.110739,-1.0,7556.0
price_increased_count_yy,float64,4894,3217,614,0.0000,NaN,0.144082,-1.0,57.0
price_increased_share,float64,5508,581,0,0.0055,NaN,0.014464,0.0,0.1302
price_increased_share_mm,float64,5508,3905,0,0.0000,NaN,0.064986,-1.0,68.2
price_increased_share_yy,float64,4896,642,612,-0.0009,NaN,-0.000509,-0.1175,0.1029
price_reduced_count,int64,5508,3200,0,580.0000,NaN,5142.209150,72.0,71888.0
price_reduced_count_mm,float64,5508,5336,0,0.0000,NaN,75.705571,-0.762456,40688.0
price_reduced_count_yy,float64,4896,4064,612,0.0000,NaN,0.076649,-0.8464,5.7706
price_reduced_share,float64,5508,1909,0,NaN,NaN,0.132805,0.0254,0.4089
price_reduced_share_mm,float64,5508,5438,0,0.0000,NaN,0.017725,-0.686779,1.793201
price_reduced_share_yy,float64,4896,1594,612,NaN,NaN,0.002088,-0.2464,0.3025
pending_listing_count,float64,5481,4612,27,NaN,NaN,8550.248312,0.0,82071.0
pending_listing_count_mm,float64,5507,5437,1,0.0000,NaN,75.303367,-1.0,57761.0
pending_listing_count_yy,float64,4860,3786,648,NaN,NaN,0.228948,-0.9777,16.1045
median_listing_price_per_square_foot,int64,5508,478,0,117.0000,NaN,195.895062,79.0,737.0
median_listing_price_per_square_foot_mm,float64,5508,1566,0,0.0000,NaN,1.329508,-0.11747,499.0
median_listing_price_per_square_foot_yy,float64,4896,2066,612,0.0655,NaN,0.075114,-0.095,0.4914
median_square_feet,int64,5508,1059,0,2000.0000,NaN,1908.460784,987.0,2798.0
median_square_feet_mm,float64,5508,4767,0,0.0000,NaN,17.816010,-0.100996,2640.0
median_square_feet_yy,float64,4896,1524,612,0.0000,NaN,-0.003240,-0.3058,0.2676
average_listing_price,int64,5508,5488,0,NaN,NaN,568693.404139,206417.0,1730505.0
average_listing_price_mm,float64,5508,5508,0,NaN,NaN,3871.307741,-0.451198,1262800.0
average_listing_price_yy,float64,4896,2314,612,0.0529,NaN,0.066544,-0.3896,1.0508
total_listing_count,int64,5508,5173,0,NaN,NaN,26086.285403,803.0,231347.0
total_listing_count_mm,float64,5508,5502,0,NaN,NaN,340.151316,-0.359258,194340.0
total_listing_count_yy,float64,4896,3398,612,NaN,NaN,-0.019375,-0.4954,1.1688
pending_ratio,float64,5481,4443,27,NaN,NaN,0.578411,0.0,3.212
pending_ratio_mm,float64,5507,5455,1,0.0000,NaN,0.044760,-1.0,81.0
pending_ratio_yy,float64,4861,3648,647,NaN,NaN,0.034240,-2.5872,2.5949

In [16]:
df2 = df[df['month_date_yyyymm'] >= '2017-07-01']

In [17]:
customDescription(df2)

,type,count,nunique,null,mode,least_frequent,mean,min,max
month_date_yyyymm,datetime64[ns],4896,96,0,NaN,NaN,NaN,2017-07-01 00:00:00,2025-06-01 00:00:00
state,object,4896,51,0,NaN,NaN,NaN,NaN,NaN
state_id,object,4896,51,0,NaN,NaN,NaN,NaN,NaN
median_listing_price,int64,4896,2389,0,299900.0000,NaN,371457.442402,144900.0,886500.0
median_listing_price_mm,float64,4896,4295,0,0.0000,NaN,0.005309,-0.103768,0.113545
median_listing_price_yy,float64,4896,2151,0,0.0000,NaN,0.068814,-0.2071,0.4101
active_listing_count,int64,4896,4492,0,NaN,NaN,16682.098652,720.0,182589.0
active_listing_count_mm,float64,4896,4891,0,NaN,NaN,0.000231,-0.307421,0.611643
active_listing_count_yy,float64,4896,3822,0,NaN,NaN,-0.012367,-0.7173,2.3532
median_days_on_market,int64,4896,125,0,44.0000,NaN,56.864379,13.0,152.0
median_days_on_market_mm,float64,4896,1279,0,0.0000,NaN,0.008552,-0.604651,0.5625
median_days_on_market_yy,float64,4896,2508,0,0.0000,NaN,-0.006308,-0.7155,1.6271
new_listing_count,int64,4896,3527,0,NaN,NaN,8122.767157,290.0,53332.0
new_listing_count_mm,float64,4896,4858,0,0.0000,NaN,0.015546,-0.691244,2.245726
new_listing_count_yy,float64,4896,3006,0,0.0000,NaN,-0.013270,-0.7398,2.0644
price_increased_count,int64,4896,998,0,20.0000,NaN,572.545752,0.0,9466.0
price_increased_count_mm,float64,4896,3098,0,0.0000,NaN,0.071544,-1.0,63.0
price_increased_count_yy,float64,4894,3217,2,0.0000,NaN,0.144082,-1.0,57.0
price_increased_share,float64,4896,560,0,0.0055,NaN,0.014501,0.0,0.1302
price_increased_share_mm,float64,4896,3563,0,0.0000,NaN,0.065660,-1.0,68.2
price_increased_share_yy,float64,4896,642,0,-0.0009,NaN,-0.000509,-0.1175,0.1029
price_reduced_count,int64,4896,2932,0,580.0000,NaN,4956.882761,72.0,71888.0
price_reduced_count_mm,float64,4896,4740,0,0.0000,NaN,0.026359,-0.762456,2.949778
price_reduced_count_yy,float64,4896,4064,0,0.0000,NaN,0.076649,-0.8464,5.7706
price_reduced_share,float64,4896,1856,0,NaN,NaN,0.131748,0.0254,0.4089
price_reduced_share_mm,float64,4896,4845,0,0.0000,NaN,0.016885,-0.686779,1.793201
price_reduced_share_yy,float64,4896,1594,0,NaN,NaN,0.002088,-0.2464,0.3025
pending_listing_count,float64,4873,4204,23,NaN,NaN,8709.798276,1.0,82071.0
pending_listing_count_mm,float64,4896,4840,0,0.0000,NaN,0.040064,-0.973371,79.0
pending_listing_count_yy,float64,4860,3786,36,NaN,NaN,0.228948,-0.9777,16.1045
median_listing_price_per_square_foot,int64,4896,464,0,NaN,NaN,202.355801,83.0,737.0
median_listing_price_per_square_foot_mm,float64,4896,1497,0,0.0000,NaN,0.005802,-0.11747,0.12
median_listing_price_per_square_foot_yy,float64,4896,2066,0,0.0655,NaN,0.075114,-0.095,0.4914
median_square_feet,int64,4896,1013,0,2000.0000,NaN,1906.746732,987.0,2798.0
median_square_feet_mm,float64,4896,4299,0,0.0000,NaN,-0.000337,-0.100996,0.178375
median_square_feet_yy,float64,4896,1524,0,0.0000,NaN,-0.003240,-0.3058,0.2676
average_listing_price,int64,4896,4880,0,NaN,NaN,586064.333742,210665.0,1730505.0
average_listing_price_mm,float64,4896,4896,0,NaN,NaN,0.005413,-0.451198,0.924406
average_listing_price_yy,float64,4896,2314,0,0.0529,NaN,0.066544,-0.3896,1.0508
total_listing_count,int64,4896,4622,0,NaN,NaN,25278.144199,803.0,231347.0
total_listing_count_mm,float64,4896,4892,0,NaN,NaN,0.001265,-0.359258,0.773585
total_listing_count_yy,float64,4896,3398,0,NaN,NaN,-0.019375,-0.4954,1.1688
pending_ratio,float64,4873,4085,23,NaN,NaN,0.619495,0.0003,3.212
pending_ratio_mm,float64,4896,4858,0,0.0000,NaN,0.044887,-0.972069,81.0
pending_ratio_yy,float64,4861,3648,35,NaN,NaN,0.034240,-2.5872,2.5949

In [18]:
df2[['price_increased_count_yy','pending_listing_count','pending_listing_count_yy','pending_ratio','pending_ratio_yy']] = \
    df2[['price_increased_count_yy','pending_listing_count','pending_listing_count_yy','pending_ratio','pending_ratio_yy']].fillna(0)

In [19]:
customDescription(df2)

,type,count,nunique,null,mode,least_frequent,mean,min,max
month_date_yyyymm,datetime64[ns],4896,96,0,NaN,NaN,NaN,2017-07-01 00:00:00,2025-06-01 00:00:00
state,object,4896,51,0,NaN,NaN,NaN,NaN,NaN
state_id,object,4896,51,0,NaN,NaN,NaN,NaN,NaN
median_listing_price,int64,4896,2389,0,299900.0000,NaN,371457.442402,144900.0,886500.0
median_listing_price_mm,float64,4896,4295,0,0.0000,NaN,0.005309,-0.103768,0.113545
median_listing_price_yy,float64,4896,2151,0,0.0000,NaN,0.068814,-0.2071,0.4101
active_listing_count,int64,4896,4492,0,NaN,NaN,16682.098652,720.0,182589.0
active_listing_count_mm,float64,4896,4891,0,NaN,NaN,0.000231,-0.307421,0.611643
active_listing_count_yy,float64,4896,3822,0,NaN,NaN,-0.012367,-0.7173,2.3532
median_days_on_market,int64,4896,125,0,44.0000,NaN,56.864379,13.0,152.0
median_days_on_market_mm,float64,4896,1279,0,0.0000,NaN,0.008552,-0.604651,0.5625
median_days_on_market_yy,float64,4896,2508,0,0.0000,NaN,-0.006308,-0.7155,1.6271
new_listing_count,int64,4896,3527,0,NaN,NaN,8122.767157,290.0,53332.0
new_listing_count_mm,float64,4896,4858,0,0.0000,NaN,0.015546,-0.691244,2.245726
new_listing_count_yy,float64,4896,3006,0,0.0000,NaN,-0.013270,-0.7398,2.0644
price_increased_count,int64,4896,998,0,20.0000,NaN,572.545752,0.0,9466.0
price_increased_count_mm,float64,4896,3098,0,0.0000,NaN,0.071544,-1.0,63.0
price_increased_count_yy,float64,4896,3217,0,0.0000,NaN,0.144023,-1.0,57.0
price_increased_share,float64,4896,560,0,0.0055,NaN,0.014501,0.0,0.1302
price_increased_share_mm,float64,4896,3563,0,0.0000,NaN,0.065660,-1.0,68.2
price_increased_share_yy,float64,4896,642,0,-0.0009,NaN,-0.000509,-0.1175,0.1029
price_reduced_count,int64,4896,2932,0,580.0000,NaN,4956.882761,72.0,71888.0
price_reduced_count_mm,float64,4896,4740,0,0.0000,NaN,0.026359,-0.762456,2.949778
price_reduced_count_yy,float64,4896,4064,0,0.0000,NaN,0.076649,-0.8464,5.7706
price_reduced_share,float64,4896,1856,0,NaN,NaN,0.131748,0.0254,0.4089
price_reduced_share_mm,float64,4896,4845,0,0.0000,NaN,0.016885,-0.686779,1.793201
price_reduced_share_yy,float64,4896,1594,0,NaN,NaN,0.002088,-0.2464,0.3025
pending_listing_count,float64,4896,4205,0,0.0000,NaN,8668.882149,0.0,82071.0
pending_listing_count_mm,float64,4896,4840,0,0.0000,NaN,0.040064,-0.973371,79.0
pending_listing_count_yy,float64,4896,3786,0,0.0000,NaN,0.227264,-0.9777,16.1045
median_listing_price_per_square_foot,int64,4896,464,0,NaN,NaN,202.355801,83.0,737.0
median_listing_price_per_square_foot_mm,float64,4896,1497,0,0.0000,NaN,0.005802,-0.11747,0.12
median_listing_price_per_square_foot_yy,float64,4896,2066,0,0.0655,NaN,0.075114,-0.095,0.4914
median_square_feet,int64,4896,1013,0,2000.0000,NaN,1906.746732,987.0,2798.0
median_square_feet_mm,float64,4896,4299,0,0.0000,NaN,-0.000337,-0.100996,0.178375
median_square_feet_yy,float64,4896,1524,0,0.0000,NaN,-0.003240,-0.3058,0.2676
average_listing_price,int64,4896,4880,0,NaN,NaN,586064.333742,210665.0,1730505.0
average_listing_price_mm,float64,4896,4896,0,NaN,NaN,0.005413,-0.451198,0.924406
average_listing_price_yy,float64,4896,2314,0,0.0529,NaN,0.066544,-0.3896,1.0508
total_listing_count,int64,4896,4622,0,NaN,NaN,25278.144199,803.0,231347.0
total_listing_count_mm,float64,4896,4892,0,NaN,NaN,0.001265,-0.359258,0.773585
total_listing_count_yy,float64,4896,3398,0,NaN,NaN,-0.019375,-0.4954,1.1688
pending_ratio,float64,4896,4086,0,0.0000,NaN,0.616585,0.0,3.212
pending_ratio_mm,float64,4896,4858,0,0.0000,NaN,0.044887,-0.972069,81.0
pending_ratio_yy,float64,4896,3648,0,0.0000,NaN,0.033995,-2.5872,2.5949