In [254]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [255]:
pd.set_option('display.max_columns', None)

In [256]:
county_history_df = pd.read_csv("data/County_History.csv")
State_History_df = pd.read_csv("data/State_History.csv")

In [257]:
county_history_df

,month_date_yyyymm,county_fips,county_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202508,31133,"pawnee, ne",149000.0,-0.0025,0.0643,7.0,0.0000,0.7500,64.0,0.2271,0.3368,0.0,-1.0000,NaN,0.0,NaN,NaN,0.0000,0.0000,0.0000,0.0,-1.0000,NaN,0.0000,-0.2500,0.0000,2.0,1.0000,-0.6000,71.0,0.0179,-0.2470,1782.0,-0.1299,0.0719,298027.0,0.0129,0.6425,9.0,0.1250,0.0000,0.2857,0.1429,-0.9643,0.0
1,202508,13067,"cobb, ga",450000.0,-0.0270,-0.0050,2683.0,-0.0228,0.2728,50.0,0.0989,0.2195,992.0,-0.0798,0.004,48.0,0.3333,-0.0769,0.0104,0.0026,-0.0025,1164.0,-0.1466,0.1279,0.2528,-0.0286,-0.0113,955.0,-0.0309,0.0437,207.0,0.0003,-0.0161,2241.0,-0.0269,-0.0029,575614.0,-0.0194,-0.0134,3634.0,-0.0150,0.2041,0.3559,-0.0030,-0.0781,0.0
2,202508,54089,"summers, wv",252450.0,0.0049,0.5300,37.0,0.2333,-0.0976,47.0,-0.0647,-0.5104,16.0,0.6000,3.000,0.0,NaN,NaN,0.0000,0.0000,0.0000,12.0,0.5000,0.0000,0.1538,0.0024,-0.0567,11.0,-0.0833,-0.0833,163.0,-0.0028,0.1692,1392.0,0.0000,0.1747,306508.0,-0.0243,0.1575,50.0,0.1765,-0.0566,0.2973,-0.1027,0.0046,1.0
3,202508,30033,"garfield, mt",224950.0,-0.1178,-0.4858,4.0,-0.2000,-0.3333,74.0,0.0278,0.0278,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,0.0000,0.0000,0.0,NaN,NaN,0.0000,0.0000,0.0000,1.0,NaN,-0.5000,105.0,-0.1448,-0.5093,1446.0,0.0094,-0.3048,211975.0,-0.1841,-0.8571,5.0,0.0000,-0.3750,0.2500,NaN,-0.0833,1.0
4,202508,48411,"san saba, tx",249000.0,-0.0945,-0.2095,28.0,0.0370,0.2727,94.0,0.0447,-0.0410,4.0,0.0000,0.000,0.0,NaN,NaN,0.0000,0.0000,0.0000,4.0,1.0000,0.0000,0.1429,0.0804,0.0179,2.0,0.5000,-0.7500,185.0,-0.0076,-0.1169,1440.0,-0.0394,-0.2492,714483.0,-0.0666,0.1899,29.0,0.0357,0.0741,0.0536,0.0165,-0.2192,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341420,201607,1023,"choctaw, al",215000.0,NaN,NaN,1.0,NaN,NaN,124.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,74.0,NaN,NaN,2894.0,NaN,NaN,215000.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
341421,201607,46077,"kingsbury, sd",87950.0,NaN,NaN,4.0,NaN,NaN,50.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,2064.0,NaN,NaN,94950.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
341422,201607,40151,"woods, ok",105000.0,NaN,NaN,2.0,NaN,NaN,60.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,80.0,NaN,NaN,1821.0,NaN,NaN,105000.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
341423,201607,2060,"bristol bay borough, ak",85000.0,NaN,NaN,1.0,NaN,NaN,136.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,177.0,NaN,NaN,480.0,NaN,NaN,85000.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
341424,201607,2068,"denali borough, ak",128750.0,NaN,NaN,16.0,NaN,NaN,71.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,4.0,NaN,NaN,0.1290,NaN,NaN,NaN,NaN,NaN,97.0,NaN,NaN,1140.0,NaN,NaN,153169.0,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN

In [258]:
county_history_df['month_date_yyyymm'] = pd.to_datetime(county_history_df['month_date_yyyymm'].astype(str), format='%Y%m')

In [259]:
county_history_df

,month_date_yyyymm,county_fips,county_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,2025-08-01,31133,"pawnee, ne",149000.0,-0.0025,0.0643,7.0,0.0000,0.7500,64.0,0.2271,0.3368,0.0,-1.0000,NaN,0.0,NaN,NaN,0.0000,0.0000,0.0000,0.0,-1.0000,NaN,0.0000,-0.2500,0.0000,2.0,1.0000,-0.6000,71.0,0.0179,-0.2470,1782.0,-0.1299,0.0719,298027.0,0.0129,0.6425,9.0,0.1250,0.0000,0.2857,0.1429,-0.9643,0.0
1,2025-08-01,13067,"cobb, ga",450000.0,-0.0270,-0.0050,2683.0,-0.0228,0.2728,50.0,0.0989,0.2195,992.0,-0.0798,0.004,48.0,0.3333,-0.0769,0.0104,0.0026,-0.0025,1164.0,-0.1466,0.1279,0.2528,-0.0286,-0.0113,955.0,-0.0309,0.0437,207.0,0.0003,-0.0161,2241.0,-0.0269,-0.0029,575614.0,-0.0194,-0.0134,3634.0,-0.0150,0.2041,0.3559,-0.0030,-0.0781,0.0
2,2025-08-01,54089,"summers, wv",252450.0,0.0049,0.5300,37.0,0.2333,-0.0976,47.0,-0.0647,-0.5104,16.0,0.6000,3.000,0.0,NaN,NaN,0.0000,0.0000,0.0000,12.0,0.5000,0.0000,0.1538,0.0024,-0.0567,11.0,-0.0833,-0.0833,163.0,-0.0028,0.1692,1392.0,0.0000,0.1747,306508.0,-0.0243,0.1575,50.0,0.1765,-0.0566,0.2973,-0.1027,0.0046,1.0
3,2025-08-01,30033,"garfield, mt",224950.0,-0.1178,-0.4858,4.0,-0.2000,-0.3333,74.0,0.0278,0.0278,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,0.0000,0.0000,0.0,NaN,NaN,0.0000,0.0000,0.0000,1.0,NaN,-0.5000,105.0,-0.1448,-0.5093,1446.0,0.0094,-0.3048,211975.0,-0.1841,-0.8571,5.0,0.0000,-0.3750,0.2500,NaN,-0.0833,1.0
4,2025-08-01,48411,"san saba, tx",249000.0,-0.0945,-0.2095,28.0,0.0370,0.2727,94.0,0.0447,-0.0410,4.0,0.0000,0.000,0.0,NaN,NaN,0.0000,0.0000,0.0000,4.0,1.0000,0.0000,0.1429,0.0804,0.0179,2.0,0.5000,-0.7500,185.0,-0.0076,-0.1169,1440.0,-0.0394,-0.2492,714483.0,-0.0666,0.1899,29.0,0.0357,0.0741,0.0536,0.0165,-0.2192,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341420,2016-07-01,1023,"choctaw, al",215000.0,NaN,NaN,1.0,NaN,NaN,124.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,74.0,NaN,NaN,2894.0,NaN,NaN,215000.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
341421,2016-07-01,46077,"kingsbury, sd",87950.0,NaN,NaN,4.0,NaN,NaN,50.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,2064.0,NaN,NaN,94950.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
341422,2016-07-01,40151,"woods, ok",105000.0,NaN,NaN,2.0,NaN,NaN,60.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,80.0,NaN,NaN,1821.0,NaN,NaN,105000.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
341423,2016-07-01,2060,"bristol bay borough, ak",85000.0,NaN,NaN,1.0,NaN,NaN,136.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,177.0,NaN,NaN,480.0,NaN,NaN,85000.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
341424,2016-07-01,2068,"denali borough, ak",128750.0,NaN,NaN,16.0,NaN,NaN,71.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,4.0,NaN,NaN,0.1290,NaN,NaN,NaN,NaN,NaN,97.0,NaN,NaN,1140.0,NaN,NaN,153169.0,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN

In [260]:
def customDescription(df: pd.DataFrame, numeric_only: bool = False):
    if numeric_only:
        df = df.select_dtypes(include=np.number)
    
    desc = pd.DataFrame(index=df.columns.to_list())
    desc['type'] = df.dtypes
    desc['count'] = df.count()
    desc['nunique'] = df.nunique()
    desc['null'] = df.isnull().sum()
    
    # Calculate mode and handle multiple modes
    modes = df.mode()
    desc['mode'] = np.nan  # Default to NaN
    for col in df.columns:
        if len(modes[col].dropna()) == 1:  # Single mode exists
            desc.loc[col, 'mode'] = modes[col].iloc[0]
        else:  # Multiple modes
            desc.loc[col, 'mode'] = np.nan

    # Calculate least frequent value
    desc['least_frequent'] = np.nan  # Default to NaN
    for col in df.columns:
        value_counts = df[col].value_counts(dropna=False)
        if not value_counts.empty:
            least_freq_count = value_counts.min()  # Find the minimum frequency
            least_freq_values = value_counts[value_counts == least_freq_count].index
            
            if len(least_freq_values) == 1:  # If exactly one least frequent value exists
                desc.loc[col, 'least_frequent'] = least_freq_values[0]
            else:  # Multiple least frequent values
                desc.loc[col, 'least_frequent'] = np.nan
    
    # Handle numeric columns
    numeric_cols = df.select_dtypes(include=np.number)
    if not numeric_cols.empty:
        numeric_desc = numeric_cols.describe().T.drop(columns=['count', 'std', '25%', '50%', '75%'], axis=1)
        for col in numeric_cols.columns:
            desc.loc[col, 'mean'] = numeric_desc.loc[col, 'mean']
            desc.loc[col, 'min'] = numeric_desc.loc[col, 'min']
            desc.loc[col, 'max'] = numeric_desc.loc[col, 'max']
    
    # Handle datetime columns
    datetime_cols = df.select_dtypes(include=['datetime64[ns]', 'datetime64[ns, UTC]'])
    for col in datetime_cols.columns:
        desc.loc[col, 'min'] = df[col].min()
        desc.loc[col, 'max'] = df[col].max()
    
    return desc

In [261]:
df = county_history_df.copy()

In [262]:
customDescription(df)

,type,count,nunique,null,mode,least_frequent,mean,min,max
month_date_yyyymm,datetime64[ns],341425,110,0,NaN,NaN,NaN,2016-07-01 00:00:00,2025-08-01 00:00:00
county_fips,int64,341425,3141,0,NaN,48261.0,30308.526710,1001.0,56045.0
county_name,object,341425,3135,0,NaN,"kenedy, tx",NaN,NaN,NaN
median_listing_price,float64,341355,51975,70,149900.0,NaN,266651.175993,1311.0,13000000.0
median_listing_price_mm,float64,303900,11909,37525,0.0,NaN,0.018215,-0.9971,570.3196
median_listing_price_yy,float64,302598,20430,38827,0.0,NaN,0.125137,-0.9968,222.8749
active_listing_count,float64,341380,5982,45,1.0,NaN,291.233391,0.0,23258.0
active_listing_count_mm,float64,303830,7988,37595,0.0,NaN,0.011154,-1.0,32.5
active_listing_count_yy,float64,302449,19378,38976,0.0,NaN,0.071654,-1.0,91.5
median_days_on_market,float64,341042,365,383,59.0,NaN,73.946071,1.0,365.0
median_days_on_market_mm,float64,303594,16421,37831,0.0,NaN,0.044884,-0.9967,114.0
median_days_on_market_yy,float64,302169,24949,39256,0.0,NaN,0.099221,-0.9948,266.0
new_listing_count,float64,341382,2269,43,0.0,NaN,133.046716,0.0,9888.0
new_listing_count_mm,float64,275717,9841,65708,0.0,NaN,0.059092,-1.0,17.0
new_listing_count_yy,float64,274415,9374,67010,0.0,NaN,0.052133,-1.0,49.0
price_increased_count,float64,341382,492,43,0.0,NaN,9.111986,0.0,1666.0
price_increased_count_mm,float64,87790,3896,253635,-1.0,NaN,-0.024384,-1.0,119.0
price_increased_count_yy,float64,89879,4989,251546,-1.0,NaN,0.027591,-1.0,85.0
price_increased_share,float64,341281,1717,144,0.0,NaN,0.005587,0.0,4.0
price_increased_share_mm,float64,303974,2040,37451,0.0,NaN,-0.000037,-1.3333,4.0
price_increased_share_yy,float64,302734,2643,38691,0.0,NaN,-0.000331,-4.0,1.3333
price_reduced_count,float64,341382,1923,43,0.0,NaN,84.265111,0.0,12596.0
price_reduced_count_mm,float64,255434,9197,85991,0.0,NaN,0.059348,-1.0,15.0
price_reduced_count_yy,float64,253753,13736,87672,0.0,NaN,0.139358,-1.0,129.0
price_reduced_share,float64,341281,3911,144,0.0,NaN,0.110751,0.0,4.0
price_reduced_share_mm,float64,303974,5598,37451,0.0,NaN,0.000480,-4.0,4.0
price_reduced_share_yy,float64,302734,5998,38691,0.0,NaN,0.004277,-4.0,4.0
pending_listing_count,float64,316402,4070,25023,1.0,NaN,151.063568,0.0,14211.0
pending_listing_count_mm,float64,280857,10231,60568,0.0,NaN,0.124332,-1.0,1579.0
pending_listing_count_yy,float64,271783,20739,69642,0.0,NaN,1.280964,-1.0,2843.0
median_listing_price_per_square_foot,float64,341088,1374,337,88.0,NaN,141.969099,0.0,56250.0
median_listing_price_per_square_foot_mm,float64,303675,9794,37750,0.0,NaN,0.013026,-0.9963,454.3632
median_listing_price_per_square_foot_yy,float64,302266,16822,39159,0.0,NaN,0.109284,-0.9982,996.1223
median_square_feet,float64,341097,3322,328,1800.0,NaN,1871.517146,4.0,30902.0
median_square_feet_mm,float64,303682,8552,37743,0.0,NaN,0.004039,-0.9957,224.25
median_square_feet_yy,float64,302271,13292,39154,0.0,NaN,0.013312,-0.9968,363.0
average_listing_price,float64,341355,251071,70,85000.0,NaN,369309.439182,5000.0,142882807.0
average_listing_price_mm,float64,303900,11261,37525,0.0,NaN,0.029188,-0.9997,3190.7232
average_listing_price_yy,float64,302598,22577,38827,0.0,NaN,0.152311,-0.9995,1941.8273
total_listing_count,float64,341382,7705,43,1.0,NaN,429.936318,0.0,33580.0
total_listing_count_mm,float64,304042,7608,37383,0.0,NaN,0.009493,-1.0,32.5
total_listing_count_yy,float64,302781,16016,38644,0.0,NaN,0.058740,-1.0,91.5
pending_ratio,float64,316269,22226,25156,0.5,NaN,0.520634,0.0,11.5
pending_ratio_mm,float64,281920,14786,59505,0.0,NaN,0.002405,-9.0833,9.1875
pending_ratio_yy,float64,273682,29190,67743,0.0,NaN,0.029240,-10.3929,11.2273
quality_flag,float64,304485,2,36940,0.0,NaN,0.324926,0.0,1.0

In [263]:
df['state_id'] = df['county_name'].str.split(', ').str[1]

In [264]:
df['state_id'] = df['state_id'].str.upper()

In [265]:
df['county_name'] = df['county_name'].str.split(',').str[0]

In [266]:
df = pd.merge(df, State_History_df[['state_id', 'state']].drop_duplicates(), on='state_id', how='left')

In [267]:
df[df['state_id'] == 'WV']

,month_date_yyyymm,county_fips,county_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,state_id,state
2,2025-08-01,54089,summers,252450.0,0.0049,0.5300,37.0,0.2333,-0.0976,47.0,-0.0647,-0.5104,16.0,0.6000,3.0000,0.0,NaN,NaN,0.0000,0.0,0.0,12.0,0.5000,0.0000,0.1538,0.0024,-0.0567,11.0,-0.0833,-0.0833,163.0,-0.0028,0.1692,1392.0,0.0000,0.1747,306508.0,-0.0243,0.1575,50.0,0.1765,-0.0566,0.2973,-0.1027,0.0046,1.0,WV,West Virginia
33,2025-08-01,54065,morgan,369900.0,0.0578,0.1209,90.0,0.0843,0.1250,59.0,0.1939,-0.0565,44.0,0.2222,0.2222,0.0,NaN,NaN,0.0000,0.0,0.0,28.0,0.0000,0.4000,0.1739,0.0042,0.0449,39.0,-0.0930,0.0541,210.0,-0.0361,0.0152,1754.0,0.0538,0.1186,407775.0,0.0646,0.1719,129.0,0.0320,0.1217,0.4333,-0.0847,-0.0292,0.0,WV,West Virginia
109,2025-08-01,54031,hardy,350000.0,-0.1765,0.2073,58.0,0.3333,0.6111,67.0,-0.0219,0.0984,20.0,0.1111,0.2500,0.0,NaN,NaN,0.0000,0.0,0.0,12.0,-0.1429,0.0000,0.1250,-0.1091,-0.0308,12.0,-0.0400,0.0000,221.0,-0.0444,0.1723,1792.0,-0.0502,0.1443,379168.0,-0.0982,0.1521,69.0,0.2321,0.4082,0.2069,-0.0805,-0.1264,0.0,WV,West Virginia
348,2025-08-01,54069,ohio,209500.0,-0.0434,0.3098,95.0,0.0000,-0.0306,50.0,0.2195,-0.1304,40.0,-0.0476,-0.0909,0.0,NaN,NaN,0.0000,0.0,0.0,32.0,-0.0588,-0.1111,0.1569,-0.0171,-0.0500,66.0,0.0909,0.2000,133.0,0.0378,0.1519,1648.0,-0.0573,0.0098,243948.0,-0.0765,0.0786,160.0,0.0323,0.0667,0.6947,0.0579,0.1335,0.0,WV,West Virginia
473,2025-08-01,54075,pocahontas,229000.0,-0.0886,0.0656,122.0,0.0000,-0.0240,95.0,0.1656,0.0053,24.0,0.3333,0.0000,0.0,NaN,NaN,0.0000,0.0,0.0,12.0,-0.1429,0.0000,0.0702,-0.0123,0.0028,23.0,-0.1636,-0.2581,277.0,0.0188,-0.0243,984.0,-0.1051,0.3131,333988.0,-0.0156,0.1026,147.0,-0.0101,-0.0455,0.1885,-0.0369,-0.0595,0.0,WV,West Virginia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341202,2016-07-01,54047,mcdowell,39990.0,NaN,NaN,22.0,NaN,NaN,60.0,NaN,NaN,4.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,4.0,NaN,NaN,0.1290,NaN,NaN,2.0,NaN,NaN,31.0,NaN,NaN,1456.0,NaN,NaN,56390.0,NaN,NaN,24.0,NaN,NaN,0.0909,NaN,NaN,NaN,WV,West Virginia
341209,2016-07-01,54061,monongalia,239950.0,NaN,NaN,617.0,NaN,NaN,75.0,NaN,NaN,108.0,NaN,NaN,4.0,NaN,NaN,0.0051,NaN,NaN,108.0,NaN,NaN,0.1224,NaN,NaN,39.0,NaN,NaN,125.0,NaN,NaN,1925.0,NaN,NaN,299286.0,NaN,NaN,660.0,NaN,NaN,0.0632,NaN,NaN,NaN,WV,West Virginia
341243,2016-07-01,54103,wetzel,119000.0,NaN,NaN,51.0,NaN,NaN,68.0,NaN,NaN,16.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,8.0,NaN,NaN,0.0784,NaN,NaN,19.0,NaN,NaN,74.0,NaN,NaN,1451.0,NaN,NaN,125119.0,NaN,NaN,69.0,NaN,NaN,0.3725,NaN,NaN,NaN,WV,West Virginia
341278,2016-07-01,54031,hardy,176950.0,NaN,NaN,145.0,NaN,NaN,89.0,NaN,NaN,20.0,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,12.0,NaN,NaN,0.0736,NaN,NaN,2.0,NaN,NaN,119.0,NaN,NaN,1602.0,NaN,NaN,218210.0,NaN,NaN,148.0,NaN,NaN,0.0138,NaN,NaN,NaN,WV,West Virginia
341342,2016-07-01,54055,mercer,119900.0,NaN,NaN,377.0,NaN,NaN,82.0,NaN,NaN,84.0,NaN,NaN,4.0,NaN,NaN,0.0083,NaN,NaN,68.0,NaN,NaN,0.1528,NaN,NaN,NaN,NaN,NaN,72.0,NaN,NaN,1650.0,NaN,NaN,157110.0,NaN,NaN,377.0,NaN,NaN,NaN,NaN,NaN,NaN,WV,West Virginia

In [268]:
# Sort by state and month
df = df.sort_values(["state", "month_date_yyyymm"])

def recompute_mm(df, base_col, mm_col):
    # Compute pct_change
    df[mm_col] = df.groupby("state")[base_col].pct_change()

    # Replace inf values with the base_col (new month value)
    inf_mask = df[mm_col].replace([np.inf, -np.inf], np.nan).isna() & df[base_col].notna()
    df.loc[inf_mask, mm_col] = df.loc[inf_mask, base_col]

    return df

In [269]:
# You can loop over all *_mm cols systematically:
base_to_mm = {
    "median_listing_price": "median_listing_price_mm",
    "active_listing_count": "active_listing_count_mm",
    "median_days_on_market": "median_days_on_market_mm",
    "new_listing_count": "new_listing_count_mm",
    "price_increased_count": "price_increased_count_mm",
    "price_increased_share": "price_increased_share_mm",
    "price_reduced_count": "price_reduced_count_mm",
    "price_reduced_share": "price_reduced_share_mm",
    "pending_listing_count": "pending_listing_count_mm",
    "median_listing_price_per_square_foot": "median_listing_price_per_square_foot_mm",
    "median_square_feet": "median_square_feet_mm",
    "average_listing_price": "average_listing_price_mm",
    "total_listing_count": "total_listing_count_mm",
    "pending_ratio": "pending_ratio_mm"
}

for base, mm in base_to_mm.items():
    if base in df.columns and mm in df.columns:
        df = recompute_mm(df, base, mm)

In [270]:
df.reset_index(drop=True, inplace=True)
df.drop(columns=['quality_flag'], inplace=True, errors='ignore')
df.drop(columns=['county_fips'], inplace=True, errors='ignore')
df

,month_date_yyyymm,county_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,state_id,state
0,2016-07-01,crenshaw,129900.0,129900.000000,NaN,29.0,29.000000,NaN,137.0,137.000000,NaN,8.0,8.000000,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.000000,NaN,0.0000,0.000000,NaN,1.0,1.000000,NaN,60.0,60.000000,NaN,2045.0,2045.000000,NaN,146597.0,146597.000000,NaN,30.0,30.000000,NaN,0.0345,0.034500,NaN,AL,Alabama
1,2016-07-01,coffee,154900.0,0.192456,NaN,436.0,14.034483,NaN,75.0,-0.452555,NaN,76.0,8.500000,NaN,0.0,0.0,NaN,0.0,0.0,NaN,76.0,76.000000,NaN,0.1439,0.143900,NaN,NaN,0.000000,NaN,83.0,0.383333,NaN,1971.0,-0.036186,NaN,183810.0,0.253846,NaN,436.0,13.533333,NaN,NaN,0.000000,NaN,AL,Alabama
2,2016-07-01,covington,150000.0,-0.031633,NaN,283.0,-0.350917,NaN,112.0,0.493333,NaN,44.0,-0.421053,NaN,0.0,0.0,NaN,0.0,0.0,NaN,32.0,-0.578947,NaN,0.0976,-0.321751,NaN,NaN,0.000000,NaN,61.0,-0.265060,NaN,2155.0,0.093354,NaN,184383.0,0.003117,NaN,283.0,-0.350917,NaN,NaN,0.000000,NaN,AL,Alabama
3,2016-07-01,walker,159500.0,0.063333,NaN,370.0,0.307420,NaN,86.0,-0.232143,NaN,68.0,0.545455,NaN,0.0,0.0,NaN,0.0,0.0,NaN,40.0,0.250000,NaN,0.0955,-0.021516,NaN,6.0,5.000000,NaN,76.0,0.245902,NaN,1949.0,-0.095592,NaN,204481.0,0.109001,NaN,375.0,0.325088,NaN,0.0162,-0.530435,NaN,AL,Alabama
4,2016-07-01,dale,122900.0,-0.229467,NaN,285.0,-0.229730,NaN,81.0,-0.058140,NaN,52.0,-0.235294,NaN,0.0,0.0,NaN,0.0,0.0,NaN,44.0,0.100000,NaN,0.1209,0.265969,NaN,NaN,0.000000,NaN,69.0,-0.092105,NaN,1724.0,-0.115444,NaN,145896.0,-0.286506,NaN,285.0,-0.240000,NaN,NaN,0.000000,NaN,AL,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341420,2025-08-01,park,572250.0,0.515894,-0.0447,204.0,0.478261,0.0355,89.0,0.780000,0.1867,44.0,0.100000,-0.2143,0.0,0.0,NaN,0.0,0.0,0.0,72.0,0.384615,0.3846,0.2449,0.159016,0.0911,57.0,0.075472,-0.0656,269.0,0.630303,-0.0444,2336.0,-0.041051,-0.0102,919901.0,1.007737,0.0051,259.0,0.370370,0.0039,0.2794,-0.272585,-0.0302,WY,Wyoming
341421,2025-08-01,crook,640000.0,0.118392,-0.0116,57.0,-0.720588,0.1875,104.0,0.168539,0.8087,20.0,-0.545455,0.6667,0.0,0.0,NaN,0.0,0.0,0.0,4.0,-0.944444,-0.5000,0.0615,-0.748877,-0.0579,8.0,-0.859649,-0.3846,274.0,0.018587,-0.0083,2254.0,-0.035103,-0.0261,1198365.0,0.302711,-0.0207,62.0,-0.760618,0.0164,0.1404,-0.497495,-0.1305,WY,Wyoming
341422,2025-08-01,natrona,350000.0,-0.453125,-0.0835,267.0,3.684211,0.2594,39.0,-0.625000,0.0694,132.0,5.600000,0.0313,0.0,0.0,NaN,0.0,0.0,0.0,96.0,23.000000,0.3333,0.2110,2.430894,0.0116,1.0,-0.875000,-0.3333,181.0,-0.339416,0.0160,2176.0,-0.034605,-0.0320,624885.0,-0.478552,0.2023,267.0,3.306452,0.2535,0.0037,-0.973647,-0.0033,WY,Wyoming
341423,2025-08-01,goshen,295000.0,-0.157143,-0.0484,67.0,-0.749064,0.0806,81.0,1.076923,0.0321,16.0,-0.878788,0.3333,0.0,0.0,NaN,0.0,0.0,0.0,16.0,-0.833333,0.3333,0.1600,-0.241706,-0.0139,1.0,0.000000,0.0000,133.0,-0.265193,0.0233,1860.0,-0.145221,-0.1599,386301.0,-0.381805,-0.0020,68.0,-0.745318,0.0794,0.0149,3.027027,-0.0012,WY,Wyoming
341424,2025-08-01,hot springs,274900.0,-0.068136,-0.1164,21.0,-0.686567,-0.2759,107.0,0.320988,0.0190,4.0,-0.750000,-0.5000,0.0,0.0,NaN,0.0,0.0,0.0,4.0,-0.750000,0.0000,0.1429,-0.106875,0.0403,3.0,2.000000,0.5000,163.0,0.225564,0.1384,1797.0,-0.033871,-0.1872,306852.0,-0.205666,-0.1999,24.0,-0.647059,-0.2258,0.1429,8.590604,0.0739,WY,Wyoming

In [271]:
columns = df.columns.tolist()
columns.insert(2, columns.pop(columns.index('state')))
df = df[columns]
columns.insert(3, columns.pop(columns.index('state_id')))
df = df[columns]
df

,month_date_yyyymm,county_name,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
0,2016-07-01,crenshaw,Alabama,AL,129900.0,129900.000000,NaN,29.0,29.000000,NaN,137.0,137.000000,NaN,8.0,8.000000,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.000000,NaN,0.0000,0.000000,NaN,1.0,1.000000,NaN,60.0,60.000000,NaN,2045.0,2045.000000,NaN,146597.0,146597.000000,NaN,30.0,30.000000,NaN,0.0345,0.034500,NaN
1,2016-07-01,coffee,Alabama,AL,154900.0,0.192456,NaN,436.0,14.034483,NaN,75.0,-0.452555,NaN,76.0,8.500000,NaN,0.0,0.0,NaN,0.0,0.0,NaN,76.0,76.000000,NaN,0.1439,0.143900,NaN,NaN,0.000000,NaN,83.0,0.383333,NaN,1971.0,-0.036186,NaN,183810.0,0.253846,NaN,436.0,13.533333,NaN,NaN,0.000000,NaN
2,2016-07-01,covington,Alabama,AL,150000.0,-0.031633,NaN,283.0,-0.350917,NaN,112.0,0.493333,NaN,44.0,-0.421053,NaN,0.0,0.0,NaN,0.0,0.0,NaN,32.0,-0.578947,NaN,0.0976,-0.321751,NaN,NaN,0.000000,NaN,61.0,-0.265060,NaN,2155.0,0.093354,NaN,184383.0,0.003117,NaN,283.0,-0.350917,NaN,NaN,0.000000,NaN
3,2016-07-01,walker,Alabama,AL,159500.0,0.063333,NaN,370.0,0.307420,NaN,86.0,-0.232143,NaN,68.0,0.545455,NaN,0.0,0.0,NaN,0.0,0.0,NaN,40.0,0.250000,NaN,0.0955,-0.021516,NaN,6.0,5.000000,NaN,76.0,0.245902,NaN,1949.0,-0.095592,NaN,204481.0,0.109001,NaN,375.0,0.325088,NaN,0.0162,-0.530435,NaN
4,2016-07-01,dale,Alabama,AL,122900.0,-0.229467,NaN,285.0,-0.229730,NaN,81.0,-0.058140,NaN,52.0,-0.235294,NaN,0.0,0.0,NaN,0.0,0.0,NaN,44.0,0.100000,NaN,0.1209,0.265969,NaN,NaN,0.000000,NaN,69.0,-0.092105,NaN,1724.0,-0.115444,NaN,145896.0,-0.286506,NaN,285.0,-0.240000,NaN,NaN,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341420,2025-08-01,park,Wyoming,WY,572250.0,0.515894,-0.0447,204.0,0.478261,0.0355,89.0,0.780000,0.1867,44.0,0.100000,-0.2143,0.0,0.0,NaN,0.0,0.0,0.0,72.0,0.384615,0.3846,0.2449,0.159016,0.0911,57.0,0.075472,-0.0656,269.0,0.630303,-0.0444,2336.0,-0.041051,-0.0102,919901.0,1.007737,0.0051,259.0,0.370370,0.0039,0.2794,-0.272585,-0.0302
341421,2025-08-01,crook,Wyoming,WY,640000.0,0.118392,-0.0116,57.0,-0.720588,0.1875,104.0,0.168539,0.8087,20.0,-0.545455,0.6667,0.0,0.0,NaN,0.0,0.0,0.0,4.0,-0.944444,-0.5000,0.0615,-0.748877,-0.0579,8.0,-0.859649,-0.3846,274.0,0.018587,-0.0083,2254.0,-0.035103,-0.0261,1198365.0,0.302711,-0.0207,62.0,-0.760618,0.0164,0.1404,-0.497495,-0.1305
341422,2025-08-01,natrona,Wyoming,WY,350000.0,-0.453125,-0.0835,267.0,3.684211,0.2594,39.0,-0.625000,0.0694,132.0,5.600000,0.0313,0.0,0.0,NaN,0.0,0.0,0.0,96.0,23.000000,0.3333,0.2110,2.430894,0.0116,1.0,-0.875000,-0.3333,181.0,-0.339416,0.0160,2176.0,-0.034605,-0.0320,624885.0,-0.478552,0.2023,267.0,3.306452,0.2535,0.0037,-0.973647,-0.0033
341423,2025-08-01,goshen,Wyoming,WY,295000.0,-0.157143,-0.0484,67.0,-0.749064,0.0806,81.0,1.076923,0.0321,16.0,-0.878788,0.3333,0.0,0.0,NaN,0.0,0.0,0.0,16.0,-0.833333,0.3333,0.1600,-0.241706,-0.0139,1.0,0.000000,0.0000,133.0,-0.265193,0.0233,1860.0,-0.145221,-0.1599,386301.0,-0.381805,-0.0020,68.0,-0.745318,0.0794,0.0149,3.027027,-0.0012
341424,2025-08-01,hot springs,Wyoming,WY,274900.0,-0.068136,-0.1164,21.0,-0.686567,-0.2759,107.0,0.320988,0.0190,4.0,-0.750000,-0.5000,0.0,0.0,NaN,0.0,0.0,0.0,4.0,-0.750000,0.0000,0.1429,-0.106875,0.0403,3.0,2.000000,0.5000,163.0,0.225564,0.1384,1797.0,-0.033871,-0.1872,306852.0,-0.205666,-0.1999,24.0,-0.647059,-0.2258,0.1429,8.590604,0.0739

In [272]:
customDescription(df)

,type,count,nunique,null,mode,least_frequent,mean,min,max
month_date_yyyymm,datetime64[ns],341425,110,0,NaN,NaN,NaN,2016-07-01 00:00:00,2025-08-01 00:00:00
county_name,object,341425,1835,0,washington,kenedy,NaN,NaN,NaN
state,object,341425,51,0,Texas,District of Columbia,NaN,NaN,NaN
state_id,object,341425,51,0,TX,DC,NaN,NaN,NaN
median_listing_price,float64,341355,51975,70,149900.0,NaN,266651.175993,1311.0,13000000.0
median_listing_price_mm,float64,341425,300264,0,0.0,NaN,33.334011,-0.996986,585000.0
median_listing_price_yy,float64,302598,20430,38827,0.0,NaN,0.125137,-0.9968,222.8749
active_listing_count,float64,341380,5982,45,1.0,NaN,291.233391,0.0,23258.0
active_listing_count_mm,float64,341425,111870,0,0.0,NaN,7.095520,-1.0,15189.0
active_listing_count_yy,float64,302449,19378,38976,0.0,NaN,0.071654,-1.0,91.5
median_days_on_market,float64,341042,365,383,59.0,NaN,73.946071,1.0,365.0
median_days_on_market_mm,float64,341425,20195,0,0.0,NaN,0.187821,-0.993827,137.0
median_days_on_market_yy,float64,302169,24949,39256,0.0,NaN,0.099221,-0.9948,266.0
new_listing_count,float64,341382,2269,43,0.0,NaN,133.046716,0.0,9888.0
new_listing_count_mm,float64,341415,35606,10,-1.0,NaN,12.210575,-1.0,8484.0
new_listing_count_yy,float64,274415,9374,67010,0.0,NaN,0.052133,-1.0,49.0
price_increased_count,float64,341382,492,43,0.0,NaN,9.111986,0.0,1666.0
price_increased_count_mm,float64,341388,4001,37,0.0,NaN,4.933711,-1.0,1524.0
price_increased_count_yy,float64,89879,4989,251546,-1.0,NaN,0.027591,-1.0,85.0
price_increased_share,float64,341281,1717,144,0.0,NaN,0.005587,0.0,4.0
price_increased_share_mm,float64,341302,27356,123,0.0,NaN,-0.078917,-1.0,93.035714
price_increased_share_yy,float64,302734,2643,38691,0.0,NaN,-0.000331,-4.0,1.3333
price_reduced_count,float64,341382,1923,43,0.0,NaN,84.265111,0.0,12596.0
price_reduced_count_mm,float64,341408,24211,17,-1.0,NaN,11.062332,-1.0,9572.0
price_reduced_count_yy,float64,253753,13736,87672,0.0,NaN,0.139358,-1.0,129.0
price_reduced_share,float64,341281,3911,144,0.0,NaN,0.110751,0.0,4.0
price_reduced_share_mm,float64,341362,217235,63,-1.0,NaN,0.059895,-1.0,43.052863
price_reduced_share_yy,float64,302734,5998,38691,0.0,NaN,0.004277,-4.0,4.0
pending_listing_count,float64,316402,4070,25023,1.0,NaN,151.063568,0.0,14211.0
pending_listing_count_mm,float64,340525,64837,900,0.0,NaN,13.835587,-1.0,13595.0
pending_listing_count_yy,float64,271783,20739,69642,0.0,NaN,1.280964,-1.0,2843.0
median_listing_price_per_square_foot,float64,341088,1374,337,88.0,NaN,141.969099,0.0,56250.0
median_listing_price_per_square_foot_mm,float64,341425,50227,0,0.0,NaN,0.171420,-1.0,591.105263
median_listing_price_per_square_foot_yy,float64,302266,16822,39159,0.0,NaN,0.109284,-0.9982,996.1223
median_square_feet,float64,341097,3322,328,1800.0,NaN,1871.517146,4.0,30902.0
median_square_feet_mm,float64,341425,264880,0,0.0,NaN,0.306414,-0.998411,2611.0
median_square_feet_yy,float64,302271,13292,39154,0.0,NaN,0.013312,-0.9968,363.0
average_listing_price,float64,341355,251071,70,85000.0,NaN,369309.439182,5000.0,142882807.0
average_listing_price_mm,float64,341425,341326,0,0.0,NaN,45.208977,-0.999078,990254.0
average_listing_price_yy,float64,302598,22577,38827,0.0,NaN,0.152311,-0.9995,1941.8273
total_listing_count,float64,341382,7705,43,1.0,NaN,429.936318,0.0,33580.0
total_listing_count_mm,float64,341425,137103,0,0.0,NaN,8.656118,-1.0,24971.0
total_listing_count_yy,float64,302781,16016,38644,0.0,NaN,0.058740,-1.0,91.5
pending_ratio,float64,316269,22226,25156,0.5,NaN,0.520634,0.0,11.5
pending_ratio_mm,float64,340525,281861,900,0.0,NaN,2.507500,-1.0,3749.0
pending_ratio_yy,float64,273682,29190,67743,0.0,NaN,0.029240,-10.3929,11.2273

In [273]:
df2 = df[df['month_date_yyyymm'] >= '2017-07-01']

In [274]:
customDescription(df2)

,type,count,nunique,null,mode,least_frequent,mean,min,max
month_date_yyyymm,datetime64[ns],304485,98,0,NaN,NaN,NaN,2017-07-01 00:00:00,2025-08-01 00:00:00
county_name,object,304485,1835,0,washington,kenedy,NaN,NaN,NaN
state,object,304485,51,0,Texas,District of Columbia,NaN,NaN,NaN
state_id,object,304485,51,0,TX,DC,NaN,NaN,NaN
median_listing_price,float64,304416,49663,69,149900.0,NaN,275248.302882,1311.0,13000000.0
median_listing_price_mm,float64,304485,270895,0,0.0,NaN,0.225320,-0.996986,338.473684
median_listing_price_yy,float64,302598,20430,1887,0.0,NaN,0.125137,-0.9968,222.8749
active_listing_count,float64,304440,5621,45,1.0,NaN,275.492458,0.0,23258.0
active_listing_count_mm,float64,304485,98879,0,0.0,NaN,6.832912,-1.0,12750.0
active_listing_count_yy,float64,302449,19378,2036,0.0,NaN,0.071654,-1.0,91.5
median_days_on_market,float64,304162,365,323,51.0,NaN,72.078567,1.0,365.0
median_days_on_market_mm,float64,304485,19031,0,0.0,NaN,0.175532,-0.993827,135.0
median_days_on_market_yy,float64,302169,24949,2316,0.0,NaN,0.099221,-0.9948,266.0
new_listing_count,float64,304442,2172,43,0.0,NaN,131.583711,0.0,9688.0
new_listing_count_mm,float64,304475,32796,10,-1.0,NaN,12.127013,-1.0,8484.0
new_listing_count_yy,float64,274415,9374,30070,0.0,NaN,0.052133,-1.0,49.0
price_increased_count,float64,304442,452,43,0.0,NaN,8.664081,0.0,1666.0
price_increased_count_mm,float64,304448,3582,37,0.0,NaN,4.692690,-1.0,1524.0
price_increased_count_yy,float64,89879,4989,214606,-1.0,NaN,0.027591,-1.0,85.0
price_increased_share,float64,304366,1669,119,0.0,NaN,0.005558,0.0,4.0
price_increased_share_mm,float64,304383,24838,102,0.0,NaN,-0.082308,-1.0,93.035714
price_increased_share_yy,float64,302734,2643,1751,0.0,NaN,-0.000331,-4.0,1.3333
price_reduced_count,float64,304442,1807,43,0.0,NaN,81.302672,0.0,12596.0
price_reduced_count_mm,float64,304468,21818,17,-1.0,NaN,10.776159,-1.0,9572.0
price_reduced_count_yy,float64,253753,13736,50732,0.0,NaN,0.139358,-1.0,129.0
price_reduced_share,float64,304366,3899,119,0.0,NaN,0.111021,0.0,4.0
price_reduced_share_mm,float64,304434,195453,51,-1.0,NaN,0.058427,-1.0,38.292731
price_reduced_share_yy,float64,302734,5998,1751,0.0,NaN,0.004277,-4.0,4.0
pending_listing_count,float64,286237,3913,18248,1.0,NaN,151.526225,0.0,13716.0
pending_listing_count_mm,float64,303997,61072,488,0.0,NaN,13.025871,-1.0,12678.0
pending_listing_count_yy,float64,271783,20739,32702,0.0,NaN,1.280964,-1.0,2843.0
median_listing_price_per_square_foot,float64,304225,1356,260,100.0,NaN,146.592788,0.0,56250.0
median_listing_price_per_square_foot_mm,float64,304485,49071,0,0.0,NaN,0.153513,-1.0,591.105263
median_listing_price_per_square_foot_yy,float64,302266,16822,2219,0.0,NaN,0.109284,-0.9982,996.1223
median_square_feet,float64,304234,3242,251,1800.0,NaN,1871.778677,4.0,16149.0
median_square_feet_mm,float64,304485,241276,0,0.0,NaN,0.033720,-0.998411,275.0
median_square_feet_yy,float64,302271,13292,2214,0.0,NaN,0.013312,-0.9968,363.0
average_listing_price,float64,304416,231984,69,85000.0,NaN,381532.133571,6000.0,142882807.0
average_listing_price_mm,float64,304485,304391,0,0.0,NaN,0.285189,-0.999078,1104.69013
average_listing_price_yy,float64,302598,22577,1887,0.0,NaN,0.152311,-0.9995,1941.8273
total_listing_count,float64,304442,7267,43,1.0,NaN,416.661292,0.0,31286.0
total_listing_count_mm,float64,304485,123460,0,0.0,NaN,8.335088,-1.0,12642.0
total_listing_count_yy,float64,302781,16016,1704,0.0,NaN,0.058740,-1.0,91.5
pending_ratio,float64,286109,22201,18376,0.5,NaN,0.553495,0.0,11.5
pending_ratio_mm,float64,303997,256699,488,0.0,NaN,2.210034,-1.0,3749.0
pending_ratio_yy,float64,273682,29190,30803,0.0,NaN,0.029240,-10.3929,11.2273

In [275]:
df2[['price_increased_count_yy','pending_listing_count','pending_listing_count_yy','pending_ratio','pending_ratio_yy']] = \
    df2[['price_increased_count_yy','pending_listing_count','pending_listing_count_yy','pending_ratio','pending_ratio_yy']].fillna(0)

In [276]:
customDescription(df2)

,type,count,nunique,null,mode,least_frequent,mean,min,max
month_date_yyyymm,datetime64[ns],304485,98,0,NaN,NaN,NaN,2017-07-01 00:00:00,2025-08-01 00:00:00
county_name,object,304485,1835,0,washington,kenedy,NaN,NaN,NaN
state,object,304485,51,0,Texas,District of Columbia,NaN,NaN,NaN
state_id,object,304485,51,0,TX,DC,NaN,NaN,NaN
median_listing_price,float64,304416,49663,69,149900.0,NaN,275248.302882,1311.0,13000000.0
median_listing_price_mm,float64,304485,270895,0,0.0,NaN,0.225320,-0.996986,338.473684
median_listing_price_yy,float64,302598,20430,1887,0.0,NaN,0.125137,-0.9968,222.8749
active_listing_count,float64,304440,5621,45,1.0,NaN,275.492458,0.0,23258.0
active_listing_count_mm,float64,304485,98879,0,0.0,NaN,6.832912,-1.0,12750.0
active_listing_count_yy,float64,302449,19378,2036,0.0,NaN,0.071654,-1.0,91.5
median_days_on_market,float64,304162,365,323,51.0,NaN,72.078567,1.0,365.0
median_days_on_market_mm,float64,304485,19031,0,0.0,NaN,0.175532,-0.993827,135.0
median_days_on_market_yy,float64,302169,24949,2316,0.0,NaN,0.099221,-0.9948,266.0
new_listing_count,float64,304442,2172,43,0.0,NaN,131.583711,0.0,9688.0
new_listing_count_mm,float64,304475,32796,10,-1.0,NaN,12.127013,-1.0,8484.0
new_listing_count_yy,float64,274415,9374,30070,0.0,NaN,0.052133,-1.0,49.0
price_increased_count,float64,304442,452,43,0.0,NaN,8.664081,0.0,1666.0
price_increased_count_mm,float64,304448,3582,37,0.0,NaN,4.692690,-1.0,1524.0
price_increased_count_yy,float64,304485,4989,0,0.0,NaN,0.008144,-1.0,85.0
price_increased_share,float64,304366,1669,119,0.0,NaN,0.005558,0.0,4.0
price_increased_share_mm,float64,304383,24838,102,0.0,NaN,-0.082308,-1.0,93.035714
price_increased_share_yy,float64,302734,2643,1751,0.0,NaN,-0.000331,-4.0,1.3333
price_reduced_count,float64,304442,1807,43,0.0,NaN,81.302672,0.0,12596.0
price_reduced_count_mm,float64,304468,21818,17,-1.0,NaN,10.776159,-1.0,9572.0
price_reduced_count_yy,float64,253753,13736,50732,0.0,NaN,0.139358,-1.0,129.0
price_reduced_share,float64,304366,3899,119,0.0,NaN,0.111021,0.0,4.0
price_reduced_share_mm,float64,304434,195453,51,-1.0,NaN,0.058427,-1.0,38.292731
price_reduced_share_yy,float64,302734,5998,1751,0.0,NaN,0.004277,-4.0,4.0
pending_listing_count,float64,304485,3913,0,0.0,NaN,142.445152,0.0,13716.0
pending_listing_count_mm,float64,303997,61072,488,0.0,NaN,13.025871,-1.0,12678.0
pending_listing_count_yy,float64,304485,20739,0,0.0,NaN,1.143387,-1.0,2843.0
median_listing_price_per_square_foot,float64,304225,1356,260,100.0,NaN,146.592788,0.0,56250.0
median_listing_price_per_square_foot_mm,float64,304485,49071,0,0.0,NaN,0.153513,-1.0,591.105263
median_listing_price_per_square_foot_yy,float64,302266,16822,2219,0.0,NaN,0.109284,-0.9982,996.1223
median_square_feet,float64,304234,3242,251,1800.0,NaN,1871.778677,4.0,16149.0
median_square_feet_mm,float64,304485,241276,0,0.0,NaN,0.033720,-0.998411,275.0
median_square_feet_yy,float64,302271,13292,2214,0.0,NaN,0.013312,-0.9968,363.0
average_listing_price,float64,304416,231984,69,85000.0,NaN,381532.133571,6000.0,142882807.0
average_listing_price_mm,float64,304485,304391,0,0.0,NaN,0.285189,-0.999078,1104.69013
average_listing_price_yy,float64,302598,22577,1887,0.0,NaN,0.152311,-0.9995,1941.8273
total_listing_count,float64,304442,7267,43,1.0,NaN,416.661292,0.0,31286.0
total_listing_count_mm,float64,304485,123460,0,0.0,NaN,8.335088,-1.0,12642.0
total_listing_count_yy,float64,302781,16016,1704,0.0,NaN,0.058740,-1.0,91.5
pending_ratio,float64,304485,22201,0,0.0,NaN,0.520091,0.0,11.5
pending_ratio_mm,float64,303997,256699,488,0.0,NaN,2.210034,-1.0,3749.0
pending_ratio_yy,float64,304485,29190,0,0.0,NaN,0.026282,-10.3929,11.2273

In [277]:
# Mapping dictionary: state -> (Region, Division)
state_to_region_division = {
    # Northeast - New England
    "Connecticut": ("Northeast", "New England"),
    "Maine": ("Northeast", "New England"),
    "Massachusetts": ("Northeast", "New England"),
    "New Hampshire": ("Northeast", "New England"),
    "Rhode Island": ("Northeast", "New England"),
    "Vermont": ("Northeast", "New England"),

    # Northeast - Middle Atlantic
    "New Jersey": ("Northeast", "Middle Atlantic"),
    "New York": ("Northeast", "Middle Atlantic"),
    "Pennsylvania": ("Northeast", "Middle Atlantic"),

    # Midwest - East North Central
    "Illinois": ("Midwest", "East North Central"),
    "Indiana": ("Midwest", "East North Central"),
    "Michigan": ("Midwest", "East North Central"),
    "Ohio": ("Midwest", "East North Central"),
    "Wisconsin": ("Midwest", "East North Central"),

    # Midwest - West North Central
    "Iowa": ("Midwest", "West North Central"),
    "Kansas": ("Midwest", "West North Central"),
    "Minnesota": ("Midwest", "West North Central"),
    "Missouri": ("Midwest", "West North Central"),
    "Nebraska": ("Midwest", "West North Central"),
    "North Dakota": ("Midwest", "West North Central"),
    "South Dakota": ("Midwest", "West North Central"),

    # South - South Atlantic
    "Delaware": ("South", "South Atlantic"),
    "Florida": ("South", "South Atlantic"),
    "Georgia": ("South", "South Atlantic"),
    "Maryland": ("South", "South Atlantic"),
    "North Carolina": ("South", "South Atlantic"),
    "South Carolina": ("South", "South Atlantic"),
    "Virginia": ("South", "South Atlantic"),
    "West Virginia": ("South", "South Atlantic"),
    "District of Columbia": ("South", "South Atlantic"),

    # South - East South Central
    "Alabama": ("South", "East South Central"),
    "Kentucky": ("South", "East South Central"),
    "Mississippi": ("South", "East South Central"),
    "Tennessee": ("South", "East South Central"),

    # South - West South Central
    "Arkansas": ("South", "West South Central"),
    "Louisiana": ("South", "West South Central"),
    "Oklahoma": ("South", "West South Central"),
    "Texas": ("South", "West South Central"),

    # West - Mountain
    "Arizona": ("West", "Mountain"),
    "Colorado": ("West", "Mountain"),
    "Idaho": ("West", "Mountain"),
    "Montana": ("West", "Mountain"),
    "Nevada": ("West", "Mountain"),
    "New Mexico": ("West", "Mountain"),
    "Utah": ("West", "Mountain"),
    "Wyoming": ("West", "Mountain"),

    # West - Pacific
    "Alaska": ("West", "Pacific"),
    "California": ("West", "Pacific"),
    "Hawaii": ("West", "Pacific"),
    "Oregon": ("West", "Pacific"),
    "Washington": ("West", "Pacific"),
}

# Create Region and Division columns
df2["Region"] = df2["state"].map(lambda x: state_to_region_division.get(x, (None, None))[0])
df2["Division"] = df2["state"].map(lambda x: state_to_region_division.get(x, (None, None))[1])

In [278]:
df2['month_date_yyyymm'] = pd.to_datetime(df2['month_date_yyyymm'])
df2['year'] = df2['month_date_yyyymm'].dt.year
df2['month'] = df2['month_date_yyyymm'].dt.month

columns = df2.columns.tolist()
columns.insert(0, columns.pop(columns.index('year')))
columns.insert(1, columns.pop(columns.index('month')))
df2 = df2[columns]

df2.drop(columns=['month_date_yyyymm'], inplace=True, errors='ignore')

In [279]:
df2

,year,month,county_name,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,Region,Division
798,2017,7,coffee,Alabama,AL,175000.0,0.379039,0.1298,414.0,15.560000,-0.0505,74.0,-0.108434,-0.0133,88.0,21.000000,0.1579,0.0,0.0,0.0,0.0000,0.0000,0.0000,68.0,16.000000,-0.1053,0.1341,-0.080877,-0.0098,0.0,0.000000,0.0000,86.0,0.653846,0.0353,2027.0,0.013500,0.0284,190074.0,0.472152,0.0341,414.0,14.923077,-0.0505,0.0000,0.000000,0.0000,South,East South Central
799,2017,7,winston,Alabama,AL,304950.0,0.742571,0.0519,271.0,-0.345411,-0.0590,115.0,0.554054,-0.0171,20.0,-0.772727,-0.5455,0.0,0.0,0.0,0.0000,0.0000,0.0000,20.0,-0.705882,-0.1667,0.0733,-0.453393,0.0035,0.0,-1.000000,-1.0000,150.0,0.744186,0.0313,2000.0,-0.013320,-0.0521,352058.0,0.852215,0.0145,271.0,-0.345411,-0.0623,0.0000,-1.000000,-0.0035,South,East South Central
800,2017,7,lee,Alabama,AL,269900.0,-0.114937,0.1345,766.0,1.826568,-0.1403,73.0,-0.365217,0.0000,220.0,10.000000,-0.1406,24.0,24.0,1.0,0.0244,0.0244,0.0132,136.0,5.800000,0.0303,0.1308,0.784447,0.0150,2.0,2.000000,-0.7143,111.0,-0.260000,0.0852,2348.0,0.174000,0.0213,308417.0,-0.123960,0.0757,767.0,1.830258,-0.1440,0.0026,0.002600,-0.0052,South,East South Central
801,2017,7,bullock,Alabama,AL,124000.0,-0.540571,-0.2250,8.0,-0.989556,0.1429,132.0,0.808219,0.1794,0.0,-1.000000,NaN,0.0,-1.0,0.0,0.0000,-1.0000,0.0000,0.0,-1.000000,NaN,0.0000,-1.000000,0.0000,1.0,-0.500000,0.0000,62.0,-0.441441,-0.0319,2213.0,-0.057496,-0.1210,156363.0,-0.493014,-0.3137,9.0,-0.988266,0.2857,0.1250,47.076923,0.0000,South,East South Central
802,2017,7,bibb,Alabama,AL,132450.0,0.068145,-0.1773,44.0,4.500000,-0.3803,115.0,-0.128788,0.4313,4.0,4.000000,-0.8000,0.0,0.0,0.0,0.0000,0.0000,0.0000,4.0,4.000000,-0.6667,0.0755,0.075500,-0.0422,5.0,4.000000,0.6667,79.0,0.274194,-0.0225,1706.0,-0.229101,-0.1440,155139.0,-0.007828,-0.2019,49.0,4.444444,-0.3378,0.1136,-0.091200,0.0714,South,East South Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341420,2025,8,park,Wyoming,WY,572250.0,0.515894,-0.0447,204.0,0.478261,0.0355,89.0,0.780000,0.1867,44.0,0.100000,-0.2143,0.0,0.0,0.0,0.0000,0.0000,0.0000,72.0,0.384615,0.3846,0.2449,0.159016,0.0911,57.0,0.075472,-0.0656,269.0,0.630303,-0.0444,2336.0,-0.041051,-0.0102,919901.0,1.007737,0.0051,259.0,0.370370,0.0039,0.2794,-0.272585,-0.0302,West,Mountain
341421,2025,8,crook,Wyoming,WY,640000.0,0.118392,-0.0116,57.0,-0.720588,0.1875,104.0,0.168539,0.8087,20.0,-0.545455,0.6667,0.0,0.0,0.0,0.0000,0.0000,0.0000,4.0,-0.944444,-0.5000,0.0615,-0.748877,-0.0579,8.0,-0.859649,-0.3846,274.0,0.018587,-0.0083,2254.0,-0.035103,-0.0261,1198365.0,0.302711,-0.0207,62.0,-0.760618,0.0164,0.1404,-0.497495,-0.1305,West,Mountain
341422,2025,8,natrona,Wyoming,WY,350000.0,-0.453125,-0.0835,267.0,3.684211,0.2594,39.0,-0.625000,0.0694,132.0,5.600000,0.0313,0.0,0.0,0.0,0.0000,0.0000,0.0000,96.0,23.000000,0.3333,0.2110,2.430894,0.0116,1.0,-0.875000,-0.3333,181.0,-0.339416,0.0160,2176.0,-0.034605,-0.0320,624885.0,-0.478552,0.2023,267.0,3.306452,0.2535,0.0037,-0.973647,-0.0033,West,Mountain
341423,2025,8,goshen,Wyoming,WY,295000.0,-0.157143,-0.0484,67.0,-0.749064,0.0806,81.0,1.076923,0.0321,16.0,-0.878788,0.3333,0.0,0.0,0.0,0.0000,0.0000,0.0000,16.0,-0.833333,0.3333,0.1600,-0.241706,-0.0139,1.0,0.000000,0.0000,133.0,-0.265193,0.0233,1860.0,-0.145221,-0.1599,386301.0,-0.381805,-0.0020,68.0,-0.745318,0.0794,0.0149,3.027027,-0.0012,West,Mountain
341424,2025,8,hot springs,Wyoming,WY,274900.0,-0.068136,-0.1164,21.0,-0.686567,-0.2759,107.0,0.320988,0.0190,4.0,-0.750000,-0.5000,0.0,0.0,0.0,0.0000,0.0000,0.0000,4.0,-0.750000,0.0000,0.1429,-0.106875,0.0403,3.0,2.000000,0.5000,163.0,0.225564,0.1384,1797.0,-0.033871,-0.1872,306852.0,-0.205666,-0.1999,24.0,-0.647059,-0.2258,0.1429,8.590604,0.0739,West,Mountain

In [280]:
df = df2.fillna(method='ffill').fillna(method='bfill')

In [281]:
df

,year,month,county_name,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,Region,Division
798,2017,7,coffee,Alabama,AL,175000.0,0.379039,0.1298,414.0,15.560000,-0.0505,74.0,-0.108434,-0.0133,88.0,21.000000,0.1579,0.0,0.0,0.0,0.0000,0.0000,0.0000,68.0,16.000000,-0.1053,0.1341,-0.080877,-0.0098,0.0,0.000000,0.0000,86.0,0.653846,0.0353,2027.0,0.013500,0.0284,190074.0,0.472152,0.0341,414.0,14.923077,-0.0505,0.0000,0.000000,0.0000,South,East South Central
799,2017,7,winston,Alabama,AL,304950.0,0.742571,0.0519,271.0,-0.345411,-0.0590,115.0,0.554054,-0.0171,20.0,-0.772727,-0.5455,0.0,0.0,0.0,0.0000,0.0000,0.0000,20.0,-0.705882,-0.1667,0.0733,-0.453393,0.0035,0.0,-1.000000,-1.0000,150.0,0.744186,0.0313,2000.0,-0.013320,-0.0521,352058.0,0.852215,0.0145,271.0,-0.345411,-0.0623,0.0000,-1.000000,-0.0035,South,East South Central
800,2017,7,lee,Alabama,AL,269900.0,-0.114937,0.1345,766.0,1.826568,-0.1403,73.0,-0.365217,0.0000,220.0,10.000000,-0.1406,24.0,24.0,1.0,0.0244,0.0244,0.0132,136.0,5.800000,0.0303,0.1308,0.784447,0.0150,2.0,2.000000,-0.7143,111.0,-0.260000,0.0852,2348.0,0.174000,0.0213,308417.0,-0.123960,0.0757,767.0,1.830258,-0.1440,0.0026,0.002600,-0.0052,South,East South Central
801,2017,7,bullock,Alabama,AL,124000.0,-0.540571,-0.2250,8.0,-0.989556,0.1429,132.0,0.808219,0.1794,0.0,-1.000000,-0.1406,0.0,-1.0,0.0,0.0000,-1.0000,0.0000,0.0,-1.000000,0.0303,0.0000,-1.000000,0.0000,1.0,-0.500000,0.0000,62.0,-0.441441,-0.0319,2213.0,-0.057496,-0.1210,156363.0,-0.493014,-0.3137,9.0,-0.988266,0.2857,0.1250,47.076923,0.0000,South,East South Central
802,2017,7,bibb,Alabama,AL,132450.0,0.068145,-0.1773,44.0,4.500000,-0.3803,115.0,-0.128788,0.4313,4.0,4.000000,-0.8000,0.0,0.0,0.0,0.0000,0.0000,0.0000,4.0,4.000000,-0.6667,0.0755,0.075500,-0.0422,5.0,4.000000,0.6667,79.0,0.274194,-0.0225,1706.0,-0.229101,-0.1440,155139.0,-0.007828,-0.2019,49.0,4.444444,-0.3378,0.1136,-0.091200,0.0714,South,East South Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341420,2025,8,park,Wyoming,WY,572250.0,0.515894,-0.0447,204.0,0.478261,0.0355,89.0,0.780000,0.1867,44.0,0.100000,-0.2143,0.0,0.0,0.0,0.0000,0.0000,0.0000,72.0,0.384615,0.3846,0.2449,0.159016,0.0911,57.0,0.075472,-0.0656,269.0,0.630303,-0.0444,2336.0,-0.041051,-0.0102,919901.0,1.007737,0.0051,259.0,0.370370,0.0039,0.2794,-0.272585,-0.0302,West,Mountain
341421,2025,8,crook,Wyoming,WY,640000.0,0.118392,-0.0116,57.0,-0.720588,0.1875,104.0,0.168539,0.8087,20.0,-0.545455,0.6667,0.0,0.0,0.0,0.0000,0.0000,0.0000,4.0,-0.944444,-0.5000,0.0615,-0.748877,-0.0579,8.0,-0.859649,-0.3846,274.0,0.018587,-0.0083,2254.0,-0.035103,-0.0261,1198365.0,0.302711,-0.0207,62.0,-0.760618,0.0164,0.1404,-0.497495,-0.1305,West,Mountain
341422,2025,8,natrona,Wyoming,WY,350000.0,-0.453125,-0.0835,267.0,3.684211,0.2594,39.0,-0.625000,0.0694,132.0,5.600000,0.0313,0.0,0.0,0.0,0.0000,0.0000,0.0000,96.0,23.000000,0.3333,0.2110,2.430894,0.0116,1.0,-0.875000,-0.3333,181.0,-0.339416,0.0160,2176.0,-0.034605,-0.0320,624885.0,-0.478552,0.2023,267.0,3.306452,0.2535,0.0037,-0.973647,-0.0033,West,Mountain
341423,2025,8,goshen,Wyoming,WY,295000.0,-0.157143,-0.0484,67.0,-0.749064,0.0806,81.0,1.076923,0.0321,16.0,-0.878788,0.3333,0.0,0.0,0.0,0.0000,0.0000,0.0000,16.0,-0.833333,0.3333,0.1600,-0.241706,-0.0139,1.0,0.000000,0.0000,133.0,-0.265193,0.0233,1860.0,-0.145221,-0.1599,386301.0,-0.381805,-0.0020,68.0,-0.745318,0.0794,0.0149,3.027027,-0.0012,West,Mountain
341424,2025,8,hot springs,Wyoming,WY,274900.0,-0.068136,-0.1164,21.0,-0.686567,-0.2759,107.0,0.320988,0.0190,4.0,-0.750000,-0.5000,0.0,0.0,0.0,0.0000,0.0000,0.0000,4.0,-0.750000,0.0000,0.1429,-0.106875,0.0403,3.0,2.000000,0.5000,163.0,0.225564,0.1384,1797.0,-0.033871,-0.1872,306852.0,-0.205666,-0.1999,24.0,-0.647059,-0.2258,0.1429,8.590604,0.0739,West,Mountain

In [282]:
customDescription(df)

,type,count,nunique,null,mode,least_frequent,mean,min,max
year,int32,304485,9,0,2024.0,2017.0,2021.083906,2017.000000,2.025000e+03
month,int32,304485,12,0,8.0,NaN,6.521323,1.000000,1.200000e+01
county_name,object,304485,1835,0,washington,kenedy,NaN,NaN,NaN
state,object,304485,51,0,Texas,District of Columbia,NaN,NaN,NaN
state_id,object,304485,51,0,TX,DC,NaN,NaN,NaN
median_listing_price,float64,304485,49663,0,149900.0,NaN,275235.928407,1311.000000,1.300000e+07
median_listing_price_mm,float64,304485,270895,0,0.0,NaN,0.225320,-0.996986,3.384737e+02
median_listing_price_yy,float64,304485,20430,0,0.0,NaN,0.125871,-0.996800,2.228749e+02
active_listing_count,float64,304485,5621,0,1.0,NaN,275.484513,0.000000,2.325800e+04
active_listing_count_mm,float64,304485,98879,0,0.0,NaN,6.832912,-1.000000,1.275000e+04
active_listing_count_yy,float64,304485,19378,0,0.0,NaN,0.072930,-1.000000,9.150000e+01
median_days_on_market,float64,304485,365,0,51.0,NaN,72.102038,1.000000,3.650000e+02
median_days_on_market_mm,float64,304485,19031,0,0.0,NaN,0.175532,-0.993827,1.350000e+02
median_days_on_market_yy,float64,304485,24949,0,0.0,NaN,0.100338,-0.994800,2.660000e+02
new_listing_count,float64,304485,2172,0,0.0,NaN,131.576938,0.000000,9.688000e+03
new_listing_count_mm,float64,304485,32796,0,-1.0,NaN,12.126592,-1.000000,8.484000e+03
new_listing_count_yy,float64,304485,9374,0,0.0,NaN,0.050283,-1.000000,4.900000e+01
price_increased_count,float64,304485,452,0,0.0,NaN,8.664013,0.000000,1.666000e+03
price_increased_count_mm,float64,304485,3582,0,0.0,NaN,4.692093,-1.000000,1.524000e+03
price_increased_count_yy,float64,304485,4989,0,0.0,NaN,0.008144,-1.000000,8.500000e+01
price_increased_share,float64,304485,1669,0,0.0,NaN,0.005557,0.000000,4.000000e+00
price_increased_share_mm,float64,304485,24838,0,0.0,NaN,-0.082333,-1.000000,9.303571e+01
price_increased_share_yy,float64,304485,2643,0,0.0,NaN,-0.000332,-4.000000,1.333300e+00
price_reduced_count,float64,304485,1807,0,0.0,NaN,81.302304,0.000000,1.259600e+04
price_reduced_count_mm,float64,304485,21818,0,-1.0,NaN,10.775518,-1.000000,9.572000e+03
price_reduced_count_yy,float64,304485,13736,0,0.0,NaN,0.139512,-1.000000,1.290000e+02
price_reduced_share,float64,304485,3899,0,0.0,NaN,0.111011,0.000000,4.000000e+00
price_reduced_share_mm,float64,304485,195453,0,-1.0,NaN,0.058319,-1.000000,3.829273e+01
price_reduced_share_yy,float64,304485,5998,0,0.0,NaN,0.004296,-4.000000,4.000000e+00
pending_listing_count,float64,304485,3913,0,0.0,NaN,142.445152,0.000000,1.371600e+04
pending_listing_count_mm,float64,304485,61072,0,0.0,NaN,13.003733,-1.000000,1.267800e+04
pending_listing_count_yy,float64,304485,20739,0,0.0,NaN,1.143387,-1.000000,2.843000e+03
median_listing_price_per_square_foot,float64,304485,1356,0,100.0,NaN,146.565982,0.000000,5.625000e+04
median_listing_price_per_square_foot_mm,float64,304485,49071,0,0.0,NaN,0.153513,-1.000000,5.911053e+02
median_listing_price_per_square_foot_yy,float64,304485,16822,0,0.0,NaN,0.109615,-0.998200,9.961223e+02
median_square_feet,float64,304485,3242,0,1800.0,NaN,1871.830320,4.000000,1.614900e+04
median_square_feet_mm,float64,304485,241276,0,0.0,NaN,0.033720,-0.998411,2.750000e+02
median_square_feet_yy,float64,304485,13292,0,0.0,NaN,0.013564,-0.996800,3.630000e+02
average_listing_price,float64,304485,231984,0,85000.0,NaN,381507.645900,6000.000000,1.428828e+08
average_listing_price_mm,float64,304485,304391,0,0.0,NaN,0.285189,-0.999078,1.104690e+03
average_listing_price_yy,float64,304485,22577,0,0.0,NaN,0.153038,-0.999500,1.941827e+03
total_listing_count,float64,304485,7267,0,1.0,NaN,416.644285,0.000000,3.128600e+04
total_listing_count_mm,float64,304485,123460,0,0.0,NaN,8.335088,-1.000000,1.264200e+04
total_listing_count_yy,float64,304485,16016,0,0.0,NaN,0.059878,-1.000000,9.150000e+01
pending_ratio,float64,304485,22201,0,0.0,NaN,0.520091,0.000000,1.150000e+01
pending_ratio_mm,float64,304485,256699,0,0.0,NaN,2.205231,-1.000000,3.749000e+03
pending_ratio_yy,float64,304485,29190,0,0.0,NaN,0.026282,-10.392900,1.122730e+01
Region,object,304485,4,0,South,Northeast,NaN,NaN,NaN
Division,object,304485,9,0,West North Central,New England,NaN,NaN,NaN

In [283]:
df.to_csv("data/county_Processed.csv", index=False)