In [6]:
import pandas as pd
import os
from supabase import create_client
from get_supabase_data import get_supabase_data

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

In [7]:
url = "https://econdata.s3-us-west-2.amazonaws.com/Reports/Core/RDC_Inventory_Core_Metrics_County.csv"
df = pd.read_csv(url)

def aggregate_data(df):
    """Load dataset, aggregate, and push to Supabase""" 
    
    county_lookup = get_supabase_data("county_lookup") 
    state_lookup = get_supabase_data("state_lookup") 

    # Preprocess data
    from preprocessing_3 import preprocess_data_3
    df = preprocess_data_3(df, county_lookup, state_lookup)

    return df

In [8]:
df = aggregate_data(df)
df

c:\1 Disk D\Mora Academic\Sem 5\Data Science and Engineering Project\AI-ML-Services\ETL\dags\preprocessing_3.py:58: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill').fillna(method='bfill')

,year,month,county_num,state_num,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,...,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
13,2025,9,1,1,342725,-0.0543,-0.0066,115,-0.0378,-0.0537,...,-0.0676,359007,-0.0408,-0.0383,209,0.0398,-0.0211,0.8122,0.0811,0.0643
19,2025,9,2,1,500702,0.0016,-0.0036,3130,-0.0011,0.1143,...,0.0024,697156,-0.0063,-0.0025,3944,-0.0184,0.1091,0.2636,-0.0205,-0.0006
38,2025,9,3,1,279900,0.0000,-0.1248,108,0.0142,0.2647,...,-0.0947,387877,0.1053,0.0302,116,-0.0043,0.2486,0.0605,-0.0433,-0.0278
39,2025,9,4,1,247400,-0.0645,-0.2445,42,0.1216,0.2969,...,-0.1888,308847,-0.0065,-0.1066,53,0.1277,0.2326,0.2892,0.0459,-0.0546
17,2025,9,5,1,298225,-0.0056,0.1224,174,0.0000,0.1797,...,0.0391,372151,-0.0014,0.0120,243,0.0319,0.2899,0.3908,0.0517,0.0857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,2025,9,2985,51,345000,-0.0282,0.1129,130,0.1261,0.4885,...,0.0031,381188,-0.0330,0.0494,130,0.1261,0.4885,0.2760,0.1167,0.1316
2978,2025,9,2986,51,3478750,0.0502,0.0091,265,-0.0569,0.1991,...,0.0133,6682801,0.0361,0.0373,318,-0.0063,0.1648,0.2094,0.0706,-0.0417
2972,2025,9,2987,51,410000,0.0188,-0.0108,70,-0.0541,0.4583,...,-0.0847,481127,-0.0220,-0.0605,72,-0.0270,0.5000,0.0286,0.0706,0.0077
2988,2025,9,2988,51,238175,-0.1146,-0.1394,30,0.0000,0.0169,...,-0.1729,275345,-0.0450,-0.2328,33,-0.0152,-0.0441,0.1667,0.0000,-0.0367
2968,2025,9,2989,51,338950,-0.1881,0.0271,29,0.1400,0.5000,...,0.2140,494401,-0.1284,-0.2993,37,0.3036,0.3519,0.2632,0.1432,-0.1579

In [9]:
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

existing_data = get_supabase_data("county_market")

In [10]:
existing_data

,year,month,county_num,state_num,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,...,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
0,2019,9,687,15,235364,1.404004,-0.0944,447,7.940000,0.1857,...,-0.1704,274913,0.860852,0.0393,455,5.319445,0.1788,0.0157,-0.965870,-0.0162
1,2019,9,688,15,90489,-0.494269,-0.2396,66,0.269231,-0.1852,...,-0.0872,155552,-0.238569,0.1274,89,0.289855,-0.2054,0.3561,0.089324,-0.0267
2,2019,9,689,15,135714,0.636627,0.1555,58,-0.588653,-0.1544,...,-0.0511,174450,0.489511,0.1898,69,-0.640625,-0.0143,0.2174,-0.437516,0.1586
3,2019,9,690,15,133048,-0.272067,0.1879,45,-0.545455,-0.2241,...,0.0431,201587,-0.119246,0.3686,46,-0.705128,-0.2288,0.0000,0.000000,0.0000
4,2019,9,691,15,140752,0.555460,-0.0666,60,-0.090909,-0.2208,...,-0.0562,166930,0.073146,-0.1007,61,-0.314607,-0.2078,0.0167,-0.953103,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296030,2022,6,2205,39,207223,0.579745,0.0236,78,0.444444,-0.3362,...,-0.0207,289659,0.581756,0.0813,106,0.164835,-0.4817,0.3910,-0.405233,-0.3579
296031,2022,6,2206,39,360850,0.399593,0.2447,51,1.217391,0.2317,...,0.1693,780232,0.866486,0.8630,109,2.516129,0.0739,1.1584,2.552284,-0.3660
296032,2022,6,2207,39,129700,-0.626655,0.1288,107,-0.683432,0.1955,...,-0.0326,192077,-0.564411,0.2553,162,-0.679208,0.0319,0.5093,0.008116,-0.2337
296033,2022,6,2208,39,163725,0.262336,2.5419,39,-0.635514,-0.5465,...,0.0482,221518,0.153277,1.0323,77,-0.524691,-0.4934,1.0256,1.013744,0.2582
296034,2022,6,2209,39,247975,0.480890,-0.0641,369,6.851064,0.2907,...,-0.0253,372845,0.373142,-0.0550,746,11.433333,0.0368,1.0163,2.375291,-0.5004

In [ ]:

# Create year_month composite keys for checking
existing_data['year_month'] = existing_data['year'].astype(str) + '_' + existing_data['month'].astype(str)
df['year_month'] = df['year'].astype(str) + '_' + df['month'].astype(str)
    
# Filter out records that already exist in the database
existing_year_months = set(existing_data['year_month'])
    
if df['year_month'].isin(existing_year_months).all():
    print("All records already exist in the database. No new data to insert.")
else:
    df = df.drop('year_month', axis=1)
    existing_data = existing_data.drop('year_month', axis=1)
    new_data = pd.concat([existing_data, df]).drop_duplicates().reset_index(drop=True)

    data_to_insert = df.to_dict('records')
    supabase.table("county_market").insert(data_to_insert).execute()

    print(f"{len(data_to_insert)} new records pushed to Supabase")

In [ ]:
existing_data.sort_values(by=['year', 'month', 'county_num'], inplace=True)

In [ ]:
existing_data

In [16]:
len(existing_data[(existing_data['year'] == 2017) & (existing_data['month'] == 6)])

0

In [12]:
len(existing_data[(existing_data['year'] == 2025) & (existing_data['month'] == 9)])

3315

In [13]:
len(existing_data[(existing_data['year'] == 2025) & (existing_data['month'] == 8)])

2000

In [14]:
len(existing_data[(existing_data['year'] == 2025) & (existing_data['month'] == 7)])

2000

In [ ]:
existing_data